### ISSUE TITLE
TECH: Grundpacket Basissystem für SWW

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#1]
Ziel: Aufbau Grundpaket/Umgebung für die Schweizer Wanderwege

**Inhalt:**

- [x] Neues Repo erstellen: hitobito_kunde , About ergänzen, Lizenz festlegen
- [x] Wagon erstellen #4 
- [x] Setup der Integrationsumgebung #2
- [x] Gruppenstruktur, Rollen, Berechtigungen #5
- [x] Visuelle Anpassungen #6
- [x] Resourcen bestellen bei /sys
- [x] Mehrsprachigkeit #7
- [x] Produktionsumgebung #3 
- [x] DNS Einstellungen Kundenseite 
- [x] Wartung und Support
