### ISSUE TITLE
PEOPLE: Redirect zurück auf Webseite nach Selbstregistrierung oder Login

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#102]
Wenn sich ein Benutzer via Webseite anmelden will, aber noch kein Login hat, kann er sich Registrieren. Siehe dazu #101 . Anschliessend soll er wieder auf die Webseite redirected werden.

Für den Redirect leitet die Webseite den Benutzer mit einer redirect_uri auf das Hitobito weiter. Es ist wichtig, dass der Benutzer wieder zurück auf diese redirect_uri geleitet wird. Der Login kann an vielen Orten auf unserer Seite passieren, z.B. kann der Benutzer einen Wandervorschlag als Favorit markieren, er kann sich einloggen um die Details eines Wandervorschlags zu sehen oder auf den Admin Bereich zugreifen. Es ist daher wichtig, dass der Benutzer nach dem Login wieder zurück auf diese Seite geleitet wird.
Ob der Benutzer sich nur einloggt oder einen Account erstellt, ist für uns erst ersichtlich, wenn er wieder zurück auf unsere Seite kommt.

# Workflow

1. Benutzer besucht SWW Webseite (CMS)
2. Auf einer beliebigen Seite erfordert eine Aktion ein Login via OIDC
3. Der Benutzer wird nach Hitobito weitergeleitet für Login oder Registrierung und anschliessendes Login
4. Nach erfolgreichem Login in Hitobito wird der Benutzer wieder zurück auf die Seite aus Punkt 2. weitergeleitet
5. Der Benutzer ist zurück im CMS und erfolgreich authentifiziert und kann die Aktion aus 2. ausführen

# Tech-Spec

- Umsetzung im Core
- Neuer Parameter `after_login_redirect_uri`
- Der Parameter wird nur im Devise Session Controller sowie im SelfRegistrationController berücksichtigt
- Ist der Registrierungslink aus #117 auf der Hauptloginseite aktiv, wird der Parameter `after_login_redirect_uri` dem Target des Links appended. Klickt der Benutzer auf diesen Link, so bleibt der Parameter auch für die Selbstregistrierungsseite erhalten.
- Ist der Parameter vorhanden, wird nach einem erfolgreichen Login der Benutzer weitergeleitet
- Heute wird man nach einem erfolgreichen Login auf die Hitobito URL weitergeileitet die man initial im Browser eingegeben hat. Sicherstellen das dies auch mit diesem Feature immer noch funktioniert

# Todo

- [ ] Im Devise Session Controller den Parameter berücksichtigen und entsprechend redirecten
- [ ] Registrierungslink auf Hauptloginformseite anpassen mit param falls param vorhanden
- [ ] Parameter auch im SelfRegistrationController berücksichtigen und redirecten falls vorhanden
- [ ] Kurze und sinnvolle Dokumentation dazu schreiben (z.B. auf der OIDC doc seite?)

**Comment by mtnstar** [comment]
geht so leider nicht aus Sicherheitsgründen!

oauth hat bereits callback_uri, wird in rails session gespeichert. vielleicht funktioniert das schon dadurch.

CMS muss callback_uri entsprechend setzen. Dann wird der Benutzer nach dem Login zurück auf die Ursprungsurl im CMS weitergeleitet. Prüfen ob das auch mit der Selbstregristation funktioniert. (Session clearing)

**Comment by olibrian** [comment]
So an Cloudtec weitergegeben.
