### ISSUE TITLE
TESTIMPORT: Import von Testdaten in die Integrationsumgebung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#103]
Um das Issue https://github.com/hitobito/hitobito_sww/issues/84 zu testen wollen wir in die Integrationsumgebung einige Testuser von der alten Webseite importieren.

Import folgende User:
Test-User 1: m.boss@cloudtec.ch
Test-User 2: m.boss+SWW1@cloudtec.ch
Test-User 3: m.boss+SWW2@cloudtec.ch
Test-User 4: t.timmers@cloudtec.ch 

Daten sind auf dem internen Share (swe/projects/SWWA_SchweizerWanderwege/Hitobito/7_Verschiedenes/DBDumpWeb) abgelegt.

## Tech-Spec

- SQL Daten in lokale DB importieren
- CSV exportieren (Separator: Semicolon) **Nur Test-User 1-4**
- CSV import auf Integrationsumgebung

## ToDo

- [x] Import db dump in mysql server (z.B. mysql server hitobito docker setup)
  - erstellen db: `docker-compose exec -it db mysql -u root -p  create database cloudteccms`
  - sowas wie `docker-compose exec -it db mysql -u root -p cloudteccms < dumpfile.sql`
- [x] Export CSV
- [x] Upload auf Integrationscontainer mittels `rsync`
  - [x] Muss unter `db/seeds/production/people_cms.csv` angelegt sein
- [x] `rake import:people_cms`
- [ ] Kunde informieren

**Comment by daniel-illi** [comment]
Die erwähnten User sind nun auf der Int Umgebung importiert.
@TheWalkingLeek wer muss wie informiert werden?

**Comment by olibrian** [comment]
Danke für den Import. ich sehe die User in der Integrationsumgebung. Leider funktioniert das Anmelden mit den Usern noch nicht. Gemäss Ticket #84 sollte dies funktionieren.

**Comment by daniel-illi** [comment]
Zum Testen habe ich nochmals einen User mit bekanntem PW importiert und konnte mich mit diesem erfolgreich anmelden.
