### ISSUE TITLE
COMMON: Datensync zu Staging-Umgebung

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_sww#105]
Um weiterführende Tests zu machen, benötigt es Daten auf der Staging-Umgebung

* Welcher Datenstand soll die neue Umgebung haben? Bracht es eine regelmässige Synchronisation?
    * Gleicher Datenstand wie Prod. inkl den entsprechenden Benutzer mit Rechte
    * Sync: nächtlich Daten von Produktionsumgebung ziehen

* Externe Dienste wie Sync Mailchimp/EBICS
    * Um Fehler mit externen Diensten zu umgehen werden beim Datenabgleich Key von Mailchimp und EBICS durch ein Script aus der DB gelöscht

* Umgang mit Dokument, Anhänge von Events, Bilder, etc?
    * vorerst werden die S3-Daten nicht kopiert.

* DONMAN benötigt Zugriff via API Keys auf diese Umgebung. Soll hier der gleiche Key verwendet werden? Sicherheitstechnisch sollte meiner Meinung nach ein eigener Key für diese Umgebung verwendet werden. Einfach auch um Verwechslung der Umgebungen einzugrenzen. obr: habe für Donman entsprechende Keys in prod und staging erstellt.

# Tech-Spec

- Keine externen Diensteanbindungen erlauben
- keine API-Keys oder Zugangsdaten zu externen Dienste
- Kunde über Vertraulichkeitsanforderungen informieren
- Production weiss nichts von Staging, Staging weiss von production
- Nicht syncen: DelayedJob table, sessions table

# ToDo

- [ ] Prod-Datenstand holen
- [ ] Zugang via ServiceAccount
- [ ] API-Keys von EBICS löschen (PaymentProviderConfig)
- [ ] API-Keys von MailChimp löschen
- [ ] weitere Zugangsdaten prüfen (GroupSettings, etc.)
- [ ] Vorschlag: `rake db:import[/path/to/dump] scheduled_jobs:clear db:clean_external_credentials`
- [ ] OpenShift-Job erstellen, der dann auch vor dem Import alles herunterskalieren kann und nachher wieder hochskaliert
- [ ] Zeitpunkt im Script notieren, zu dem S3-Sync stattfinden sollte, wenn dieser noch beauftragt wird
- [ ] Sync nächtlich laufen lassen

**Comment by ThomasEllenberger** [comment]
Duplikat von und abgelöst durch: https://github.com/hitobito/hitobito_sww/issues/215
