### ISSUE TITLE
PEOPLE: Anpassung Selbstregistrierung

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#117]
Gemäss #101 sollen für SWW Anpassungen am Selbstregistrierungsformular gemacht werden. Ein Teil dieser Anpassungen können im Core, andere im Wagon gemacht werden.

## Aktuelles Form

![image](https://user-images.githubusercontent.com/655627/225577774-1c11c059-c952-4761-b0f6-b0499f25bb69.png)

## 1. Formfelder (SWW Wagon)

* E-Mail *  -> speichern in Haupt-E-Mail 
* Anrede* -> Als Dropdown speichern in Geschlecht. Auswahl: Frau, Herr, Andere
* Vorname*
* Nachname*
* Strasse -> speichern in Adresse
* Hausnummer -> speichern in Adresse
* PLZ
*  Ort
*  Geburtsdatum

Das Feld Übername streichen.
Felder mit * sind Pflichfelder und müssen ausgefüllt werden.

Anpassung im SWW Wagon

### Tech-Spec

- Im Wagon `Groups::SelfRegistrationController` sowie View files customizen
- Sicherstellen das nur die gewünschten Felder permitted werden
- Strasse, Hausnummer vor dem Persistieren in ein Feld mergen

## 2. Titel, Button Registrierungsformular (Core)

1. Anstatt «Speichern», «Anmelden» (neue/spezifische Translation im Core)
2. Neues Feld für benutzerdefinierten Titel Registrierungsformular
  - übersetzbares Feld auf Group, falls gesetzt, wird dieser Titel angezeigt. Sonst Titel wie bisherige Implementation

### Tech-Spec

- in Group Model: `translates :custom_self_registration_title`

## 3. Nutzungsbedingungen/Datenschutz Hinweise (SWW Wagon)

SWW wünscht einen eigenen Text und will nicht das bestehende Feature für den PDF Upload (Hitobito #1881) nutzen. 

Auf der Selbstregistrierungsseite sollen Hinweise zu Nutzungsbedigungen+Datenschutz angezeigt werden:

Unter den Anmeldeangaben sollte noch folgender Hinweis stehen: 

**Nutzungsbedingungen**

Indem Sie auf «Registrieren» klicken, stimmen Sie den [Nutzungsbedingungen](https://www.schweizer-wanderwege.ch/nutzungsbedingungen/de) der Schweizer Wanderwege zu.

**Datenschutz**

Weitere Informationen darüber, wie die Schweizer Wanderwege Ihre personenbezogenen Daten erfassen, verwenden, weitergeben und schützen, finden Sie in der[ Datenschutzrichtlinie](https://www.schweizer-wanderwege.ch/datenschutz/de) der Schweizer Wanderwege.

## 4. Registrierungslink auf Hauptloginseite (Core)

![image](https://user-images.githubusercontent.com/655627/225647208-17da17f8-0397-48a3-9342-49f9a92778a5.png)

Bei einer Gruppe auf der die Externe Registrierung aktiv ist, kann die Option für das Aktivieren eines Registrierungslinks aktiviert werden. Für die komplette Hitobito Instanz nur für eine Gruppe. 

![image](https://user-images.githubusercontent.com/655627/225647763-326633c1-d1d5-466b-89cc-04979d87d66e.png)

Ist die Option aktiv, wird auf der Hauptloginseite ein entsprechender Link dargestellt.

## Tech-Spec

- Neues Setting (Settings) das die Gruppen ID speichert falls diese ausgewählt wurde
- Falls abgewählt und gespeichert|Selbstregistrierung deaktivert|Gruppe wird gelöscht/archiviert|gemerged mit anderen Gruppe: Setting auf nil setzen
- Wichtig: Setting kann nur mit Admin Berechtigung bearbeitet. Read-only falls Bearbeitungsrechte auf Gruppe. 

# Todo

Priorität in folgender Reihenfolge
- [x] 1. Anpassen der Felder Registrierungsform  (SWW Wagon)
- [x] 4 Registrierungslink
- [x] 2.1 Rename Button Registrierungsformular (Core)
- [x] 2.2 Feld auf Gruppe für benutzerdefinierten Titel des Selbstregistrierungsformulars
- [x] 3 Nutzungsbedingungen/Datenschutz

**Comment by olibrian** [comment]
Hier noch die Übersetzungen für die Nutzungsbedingungen und Datenschutz

### Italienisch

**Condizioni**

Cliccando su «Registrarsi», accetti le [condizioni d'uso](https://www.sentieri-svizzeri.ch/condizioniduso) dei Sentieri Svizzeri.

 **Protezione dei dati**

Ulteriori informazioni su come i Sentieri Svizzeri raccolgono, utilizzano, divulghino e proteggano i tuoi dati personali sono disponibili nella [politica sulla privacy](https://www.sentieri-svizzeri.ch/protezionideidati) dei Sentieri Svizzeri.

### Französisch

**Conditions générales**

En cliquant sur «S'inscrire», vous acceptez les [conditions d'utilisation](https://www.suisse-rando.ch/cgp) de Suisse Rando.

 **Confidentialité**

Pour en savoir plus sur la manière dont Suisse Rando collectent, utilisent, divulguent et protègent vos données personnelles, veuillez consulter la [politique de confidentialité](http://www.suisse-rando.ch/confidentialite) de Suisse Rando.
