### ISSUE TITLE
BENUTZERKONTO: Ansicht Personen mit Benutzerkonten einschränken

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#120]
Wenn sich eine Person in Hitobito einlogt und nur eine Rolle als "Benutzerkonto" hat, sieht er zur Zeit die gesamte Struktur und Navigation. Da diese Personen nur für die Authentifizierung bei der Webseite verwendet werden, sollen sie in Hitobito nur sich selber sehen und möglichst wenig von Hitobito.

See https://github.com/hitobito/hitobito_sww/pull/121

# Tech-Spec

* Umsetzung im Core
* Neues **class_attribute** welches auf einer Rolle gesetzt werden kann:
  * **basic_permissions_only**, default: false
* Hat eine Person nur Rollen mit **basic_permissions_only**: true :
  * kann sie nur ihr eigenes Profil bearbeiten, Passwörter resetten, usw.
  * Sieht und hat nur Zugriff auf das Info Tab auf dem Profil
  * sieht die Hauptnavigation nicht
  * hat keinen Zugriff auf Events
  * hat keinen Zugriff auf Einstellungen, Labels, usw.
  * kann die Gruppenstruktur nicht auflisten (auch nicht via API)
* Hat eine Person keine Rolle, verhält sich das ganze ähnlich. Gibt es hier Synergien?  

# ToDo

- [x] Anpassungen im Core
  - [x]  TDD: Specs schreiben die die Permission prüfen (alle Cases vor der Umsetzung definieren)
  - [x] Implementation
  - [x] Dokumentation des neuen Attributes
  - [x] Durchklicken
- [x] im SWW Wagon Attribut basic_permissions_only auf true für Benutzerkonto
- [x] mind. ein Permission Check Spec im SWW Wagon

**Comment by daniel-illi** [comment]
Wie ich gerade entdeckt habe, gibt es bei GLP ebenfalls einen Mechanismus mit welchem die Hauptnavigation für gewisse Rollen ausgeblendet werden kann:
* https://github.com/hitobito/hitobito_glp/blob/master/app/models/glp/person.rb#L13
* https://github.com/hitobito/hitobito_glp/blob/master/app/models/glp/person.rb#L37

Die neue Lösung basierend auf dem `Role#basic_permissions_only` scheint mir eleganter. Jedenfalls sollte der GLP wagon wohl noch angepasst werden und ebenfalls den neuen Mechanismus verwenden...
