### ISSUE TITLE
INVOICES: Import offener Rechnungen FOs

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#13]
für den einmaligen Import pro Fachorganisation (FO) der offenen Rechnungen aus Alabus soll ein automatisierter Import gebaut werden.

Es gibt ungefähr 17 Fachorganisationen und dieser Import wird pro FO einmalig angewendet.

Alabus Daten liegen als Excel-Export vor. Export kann vor dem Import manuell in ein CSV umgewandelt werden.

Als Parameter wird die Gruppen ID des FO Layers in welche die Rechnungen importiert werden sollen angegeben.

| Alabus Attribut | Inhalt                              | Hitobito Attribut                                                          |
| --------------- | ----------------------------------- | -------------------------------------------------------------------------- |
| id              | Unqiue Alabus Personen ID           | Wird für die Zuweisung der Person in Hitobito verwendet (person#alabus_id) |
| Status          | Rechnungsstatus                     | Es werden nur Rechnungen mit Status offen importiert                       |
| Referenznummer  | Referenznummer Rechnung             | invoice#esr_number                                                         |
| Rechungsdatum   | 22.02.2022                          | invoice#sent_at                                                            |
| Erstellt am     | 22.02.2022  14:42                   | invoice#created_at                                                         |
| Kategorien      | Einzelmitglied, Doppelmitglied, ... | invoice_item1#name                                                         |
| Rechnungsbetrag | 20.00                               | invoice_item1#unit_cost, count: 1                                          |

# Tech-Spec

- rails import:invoices_fo
  - source datei: $WAGON_ROOT/db/seeds/production/invoices_fo.csv
  - parameter layer_id
- Pro Importzeile mit Status **offen** wird eine neue Rechnung in Hitobito erstellt
- Titel: "Alabus Rechnung" + Alabus Atttribut "Kategorien"
- Status der importierten Rechnung ist :sent
- Auch Rechnungen mit Betrag 0.00 werden importiert
- person über alabus_id / id export Spalte zuweisen
- Pro Rechnung je ein Item mit Name, unit_cost und count = 1

# ToDo

- [x] Rake-Task `import:invoices_fo[layer_id]` anlegen
	- [x] source datei: $WAGON_ROOT/db/seeds/production/invoices_fo.csv
	- [x] parameter layer_id
	- [ ] Details siehe Tech-Spec
