### ISSUE TITLE
INVOICE: Manuelles Rechnungsdatum

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#135]
Aktuell wird bei der Rechnungstellung immer das aktuelle Datum als Rechnungsdatum genommen. Dies ist unbefriedigend wenn die Rechnung erst später versendet wird, etwa weil diese noch von einer Druckerei gedruckt werden muss.

Das Rechnungsdatum sollte bei Rechnungen via Abo, Einzel- und Sammelrechnung manuell definiert werden können. 
Standartmässig soll beim Rechnungsdatum das heutige Datum vorausgefüllt sein.

Optional: Für das  "Fällig am" soll eine Prüfung stattfinden, dass das Datum zwingend grösser (weiter in der Zukunft ) ist als das "Rechnungsdatum".

Optional: Umsetzung auch für Mahnungen

Prüfung: Umsetzung im Core?

# Mockup

hier folgt ein Mockup ...

# Tech-Spec

- Das betroffene Feld heisst in der DB `issued_at`
- Es ist im Code sogar bereits vorgesehen, dass man dieses Feld mal selber setzen könnte: https://github.com/hitobito/hitobito/blob/master/app/models/invoice.rb#L243
- Zwar wird dieses Feld normalerweise erst später befüllt, nämlich wenn man die Rechnung aus dem Status "Entwurf" in den Status "Gestellt" bringt. Aber als pragmatische Lösung soll man das `issued_at` einfach bereits beim initialen Erstellen einer Rechnung setzen können (egal dass die Rechnung noch ein Entwurf ist).
- Umsetzung im Core

# ToDo

- [x] Im [Formular]() ein Datumsfeld `issued_at` einfügen, welches aber auch leer gelassen werden darf
- [x] Überprüfen, dass das Feld korrekt gespeichert werden kann
- [x] Überprüfen, dass der Rechnungs-Workflow weiterhin funktioniert wenn man das Feld ausfüllt, und wenn man es leer lässt
- [x] Überprüfen, dass man das Feld auch nachträglich noch bearbeiten kann
- [x] Dieselben Dinge auch für Sammelrechnungen und Rechnungsbriefe überprüfen
