### ISSUE TITLE
INVOICES: Titel im Adressblock

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#137]
Aktuell werden auf aus Hitobito erstellten Dokumenten keine Titel ("Herr" / "Frau") angezeigt.

Neu soll der Titel im Adressblock integriert werden.

Welcher Titel verwendet wird soll der folgenden Logik entsprechen: 
- ~~Wenn Benutzerdefinierte Anrede vorhanden, dann diese verwenden~~
- Der Titel wird vom Geschlecht abgeleitet: 
  - männlich = Herr
  - weiblich = Frau
  - unbekannt = leer lassen und nichts anzeigen, wie bisher
Sprachen sollen berücksichtigt werden, gemäss der "Sprache" auf der Person.

# Beispiel: 

Frau
Maxine Muster
Mustertrasse 12
3000 Musterdorf

Betrifft: Rechnungen, Mahnungen, Rechnungsbriefe, Briefe

~~Prüfen ob eine generische Lösung mit https://github.com/hitobito/hitobito/issues/1141 Sinn machen würde.~~

# Tech-Spec

- Umsetzung nur im SWW Wagon
- https://github.com/hitobito/hitobito_sww/blob/master/app/domain/sww/export/pdf/messages/letter.rb
- https://github.com/hitobito/hitobito_sww/blob/master/app/domain/sww/export/pdf/invoice/receiver_address.rb

# ToDo

- [x] Adressblock für Rechnungen anpassen
- [x] Adressblock für Briefe/Rechnungsbriefe anpassen
- [ ] PDF Generierung auch mit langen Adressen sowie Landangabe testen
- [ ] Kunde wegen allfällig neuen Übersetzungen informieren

**Comment by carlobeltrame** [comment]
"Herr" oder "Frau" sind keine Anreden, sondern Titel. Im Anrede-Feld kann man Werte auswählen wie "Sehr geehrte/r Herr/Frau [Nachname]" oder "Hallo [Vorname]". Diese Einstellung hat keinen Einfluss darauf, welcher Titel in einem Adressblock korrekt wäre. Der Titel ist nur vom Geschlecht abhängig.

Den geschlechtsabhängigen Titel im Adressblock anzuzeigen ist, wegen Platzbeschränkungen, unterschiedlichen Gender-Philosophien bei anderen Verbänden, sowie Komplikationen bei Haushaltsadressen, ein Thema für das ich keine einfache einheitliche Lösung im Core sehe.

**Comment by mtnstar** [comment]
@thaeuselmann 

Aktuell sind auf eurer Produktion folgende werde im Feld Benutzerdefiniere Anrede gespeichert:

```
"Damen und Herren",
 "Frau",
 "Herr",
 "LU",
 "AR",
 "Familie",
 "VS",
 "SG",
 "BE",
 "SZ",
 "GR",
 "FR",
 "ZG",
 "VD",
 "Herr und Frau",
 "Dr. med.",
 "Sehr geehrte Frau Hart",
 "Familien Kienberger & Dietrich",
 "Sehr geehrte Frau Steinh<C3><A4>user",
 "Markus Str<C3><A4>ssle",
 "Herr + Frau",
 "SO",
 "Frau und Herr",
 "GL",
 "Madame",
 "Monsieur",
 "Monsieur & Madame",
 "Madame & Monsieur",
...```

und viele weitere recht verschiedene Werte

Ist dir das so bewusst? sollen wir das trotzdem so wie du es oben beschrieben hast umsetzen?

Das würde dann dazu führen das Adressen dann mit dieser Vielfalt an Anreden ergänzt würde:

```
SO
Maxine Muster
Mustertrasse 12
3000 Musterdorf
```

**Comment by thaeuselmann** [comment]
Hi @mtnstar 
Danke fürs melden, das war mir so nicht bewusst. Lassen wir den Teil mit der benutzerdefinierten Anrede doch weg. Wenn wir einfach vom Geschlecht ableiten reicht das.
