### ISSUE TITLE
PEOPLE: Doubletten zusammenführen

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#138]
Beim Zusammenführen von Dubletten werden aktuell einige Daten noch nicht berücksichtigt und zusammengeführt. Dies ist nicht befriedigend da dadurch Informationen verloren gehen können.

Neu sollen dabei alle Daten berücksichtigt werden. Ziel ist es dass beim Zusammenführen keine Daten mehr verloren gehen.
Dies betrifft: Rechnungen, Mahnungen, Notizen, Mitgliedernummern, Tags?, Logs?, Abos?, Abo # Magazin, Benutzerdefinierte Anrede?, Titel?, Namenszusatz?, Anlass Anmeldungen.

Abklärung: Nach Möglichkeit sollen alte Mitgliedernummern nicht verloren gehen. Führt man zwei Datensätze zusammen welche beide eine Mitgliedernummer haben, dann soll die nicht gewählte nicht verschwinden sondern in ein anderes Feld überführt werden. Eine offene Frage ist noch wie dies umgesetzt wird. Ein neues Feld "Alte Mitgleidernummer? Als Tag? Als Notitz?

Abklären: Gibt es noch weitere Daten nebst den oben erwähnten welche aktuell bei der Zusammenführung von Dubletten noch nicht berücksichtigt werden?

Rechnungen & Mahnungen werden durch  https://github.com/hitobito/hitobito_sww/issues/139 gelöst.
Edit: Hier wurde gleich einiges mehr auch noch umgesetzt. Vor Umsetzung dieses Issues zuerst abgleichen was bereits gelöst ist und welche der Anforderungen noch offen sind.

Umsetzung im Core bei allen Feldern die im Core existieren?

# ToDo

- [x] Überprüfen, was von den Anforderungen in https://github.com/hitobito/hitobito_sww/issues/139 bereits umgesetzt wurde.
- [x] Person um MERGEABLE_ATTRS erweitern, der erstmal die PUBLIC_ATTRS enthält, aber vom Wagon aus erweitert werden kann.
- [x] People::Merger anpassen
    - Statt PUBLIC_ATTRS nur die MERGEABLE_ATTRS nutzen
    - alle associations prüfen
    - Bei vorhandenen Attributen die nicht kopierten in einer Notiz sammeln
    - verhinderte Doppelung müssen nicht aufgeführt werden (z.B. vorher und nacher die gleiche Korrespondenzsprache)
    - Notiz soll zeigen, was verloren gegangen ist, u.a. Mitgliedernummern und so.
    - Tag "just ~married~ merged" (mit vernünftigem Namen) vergeben
    - ggf. Tag "~trouble in paradise~ merge conflict" (mit vernünftigem Namen) vergeben
- [x] Specs schreiben
- [x] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by njaeggi** [comment]
Alle Attribute der alten Person werden bereits als Version im Log gespeichert, einzige neue Änderung:
- manual_member_number wird übernommen
- manual_member_number wird im Log eingetragen
