### ISSUE TITLE
SWW-spezifische Schrift für PDFs

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#142]
Für sämtliche Dokumente welche aus Hitobito exportiert werden (Rechnung, Mahnungen, Rechnungsbriefe, Briefe) soll das Schriften-Design von SWW verwendet werden:

Schriftart: Cardo
Basis-Schriftgrösse: 10 (Überschriften o.ä. entsprechend grösser/kleiner)

Ausgenommen von diesem Issue ist die Anforderung, dass zusätzlich Titel eine andere Schriftart haben sollen (Montserrat, Schriftgrösse 16, Versalien, letter-spacing 1.1). (Schätzung: +4PT Aufwand)

# Tech-Spec

- einheitliche Schriftart und -grösse
- Prawn Dokumentation: https://prawnpdf.org/manual.pdf, siehe
  - Text -> External Fonts -> Registering Families

# ToDo

- [x] Font [Cardo herunterladen](http://scholarsfonts.net/cardofnt.html#DownloadLink) und im Wagon speichern
- [x] Font-Family in customize-Methoden registrieren und font setzen:
  - [x] app/domain/export/pdf/participation.rb
  - [x] app/domain/export/pdf/messages/letter.rb
  - [x] app/domain/export/pdf/messages/letter_with_invoice.rb
  - [x] app/domain/export/pdf/invoice.rb
- [x] Alle Exporte einmal testen
- [x] Specs anpassen
- [x] Position des Mitgliederausweis nicht verämdern
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
