### ISSUE TITLE
Variable Schriftgrösse auf Mitgliederausweis

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#143]
Der SWW Druckt aus Hitobito heraus Mitgleiderausweise. Diese haben eine fixe Grösse. Hat ein Mitglied einen zu langen Namen, wird dieser aktuell einfach abgeschnitten. Dies soll nicht mehr geschehen. Stattdessen soll die Schriftgrösse Schritt für Schritt verkleinert werden, bis der ganze Name auf dem Mitgliederausweis platz hat.

Das Feld ist aktuell 69 mm breit, es passen maximal ~~31~~ 19 grosse "M"s hin. Die Schrift soll danach Punkt für Punkt verkleinert werden, damit der Name in jedem realistischem Fall komplett Platz hat.

Es wurden zwei mögliche vorgehen definiert: 
1. Das Feld wird so angepasst dass es ab einer bestimmten Anzahl an Zeichen eine kleinere Schriftgrösse hat.
2. Das Feld wird so angepasst, dass es dynamisch die Schriftgrösse ändert wenn der jeweilige Name zu lang ist.

~~Nach Absprachen mit SWW haben wir uns für Vorgehen 1 entschieden.
Das Feld soll so geändert werden, dass es ab einer bestimmten Anzahl Zeichen die Schriftgrösse verändert, so dass auch Namen die nur aus "M" bestehen immer Platz haben. Dadurch kann es sein, dass es bei manchen Namen einmal eine zu kleine Schriftgörsse verwendet, es sollte aber nicht mehr vorkommen, dass ein Name nicht platz hat und abgeschnitten wird.~~

Eine Analyse hat ergeben, dass mit prawn sehr einfach eine variable Schriftgrösse implementiert werden kann.

# Tech-Spec

- Umsetzung im SWW Wagon, da es nur den Mitgliederausweis der SWW betrifft

# ToDo
- [x] In https://github.com/hitobito/hitobito_sww/blob/master/app/domain/sww/export/pdf/messages/letter/membership_card.rb#L20 variable Schriftgrösse einfügen, je nach Zeichenlänge von `person_or_company_name(recipient)`
  - [x] Bei genügend Platz gleich wie bisher (`10.pt`)
  - [x] Bei längerem Text dynamisch kleinere Schriftgrösse, bis zu minimal `5.pt` (kleiner macht keinen Sinn mehr).
