### ISSUE TITLE
INVOICE: Logo für Rechnungen

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#144]
Aktuell sind bei Rechnungs-PDF's keine Logos enthalten.
Die SWW wünschen sich eine Möglichkeit, Logos analog den Rechnungsbriefen in den Rechnungs-PDFs zu integrieren.

Neu soll in den Rechnungseinstellungen pro Layer einstellbar sein, ob das Logo auf Rechnungen enthalten ist, oder nicht. Die Einstellungen dazu sollen in einem neuen Layout Tab auf den Rechnungseinstellungen sein.  Hier soll auch ein entsprechendes Logo hinterlegt werden können.

- Neues Layout Tab auf den Rechnungseinstellungen (bereits mit  hitobito_sww#146 umgesetzt)
- Das Logo soll an drei vordefinierten Positionen einblendbar sein:
  - Core: rechts, links, nicht anzeigen, standard: rechts
  - sww wagon: Zusätliche Position direkt über dem Einzahlungsschein (Vorlage:  [SO_Overlay_RG.pdf](https://github.com/hitobito/hitobito_sww/files/12333147/SO_Overlay_RG.pdf) )

# Tech-Spec

- Umsetzung des einstellbaren Logos im Core
- Umsetzung der zusätzlichen Logo-Position Einzahlungsschein im SWW-Wagon

# ToDo

- [x] Neue Attribute auf InvoiceConfig:
  - invoice_logo
  - invoice_logo_position, enum: :left, :right, :disabled
- [ ] ~CarrierWave image mount und uploader auf InvoiceConfig definieren~
- [x] Rechnungs-PDF anpassen sodass gemäss gewählter Einstellung Logo gerendert wird
  - Wagon-Erweiterung berücksichtigen
- [x] SWW Wagon Erweiterung mit Logo Position Einzahlungsschein
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
