### ISSUE TITLE
Mahnungen für teilbezahlte Rechnungen werden auf den Gesamtbetrag erstellt

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#145]
Wenn eine Rechnung teilbezahlt wurde, wird die Mahnung für Gesamtbetrag erstellt. Wir würden die Teilzahlungen gerne auf der Mahnung aufgeführt sehen und der Mahnbetrag soll nur die Differenz betragen.
Der Text auf der Mahnung bleibt derselbe wie bei der gleichen Mahnstufe wenn noch nichts bezahlt worden wäre.

Im Issue #38 wurde umgesetzt, dass Teilbezahlte Rechnungen nun einen eigenen Status haben.

~Offene Frage:~
Soll der Teilbezahlte Betrag vor oder nach dem Zwischentotal erscheinen?
- [ ] Mockup 1 
- [x] Mockup 2.

--> Umgesetzt soll Version 2/Mockup 2 werden, dass der Teilbezahlte Betrag unter dem Gesamtbetrag erscheint.
Wording mässig nehmen wir "Eingegangene Zahlung" und "Offener Betrag".

# Mockup

**Mockup 1:**
![image](https://github.com/hitobito/hitobito_sww/assets/124251904/77821dbd-a643-41a2-b94d-6f6aa3464288)

![Image](https://github.com/hitobito/hitobito_sww/assets/100761305/952dd644-4385-44de-8e3a-804c5718463a)

**Mockup 2:**
![Image](https://github.com/hitobito/hitobito_sww/assets/100761305/c22e6167-5b72-4cd9-a551-e0a2e7477a4c)

![Image](https://github.com/hitobito/hitobito_sww/assets/100761305/d66f04f5-3360-42ca-a8ed-260272bb6712)

# Tech-Spec

- Umsetzung im Core, dabei aber Acht geben dass nur allgemeingültige Texte verwendet werden, nichts SWW-spezifisches
- Es ist noch unklar, ob mehrere Teilzahlungen je einzeln oder zusammengezogen dargestellt werden sollen, und falls einzeln, ob das Zahlungsdatum ebenfalls vermerkt werden soll.

# ToDo

- [x] PDF-Rendering in `total_box` und/oder `total_data` in https://github.com/hitobito/hitobito/blob/master/app/domain/export/pdf/invoice/articles.rb um Auflistung der bereits zugeordneten Zahlungen dieser Rechnung ergänzen
  - [x] Pro eingegangene Zahlung eine Zeile, Inhalte ungefähr wie in Mockup 1 ersichtlich. Die zugeordneten Zahlungen müssten via `invoice.payments` verfügbar sein.
  - [x] Zahlungen sind chronologisch geordnet, nach dem `received_at` Datum das wir in hitobito haben. Es ist zu erwarten, dass dieses Datum nicht immer dem "Zahlungsdatum" entspricht, aber das macht nichts.
- [ ] Im Einzahlungsschein den Rechnungsbetrag auch auf den "Offenen Betrag" ändern
