### ISSUE TITLE
Ein-/Ausblenden von Linien auf Einzahlungsschein

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#146]
Neu soll in den Rechnungseinstellungen soll Layer ausgewählt werden, ob Rechnungen und Mahnungen inklusive Logo oben und/oder schwarzer Linie (mit Schere) beim Einzahlungsschein generiert werden sollen. Die Einstellungen dazu sollen in einem neuen Layout Tab auf den Rechnungseinstellungen sein.

Logo auf PDF_Rechnungen anzeigbar machen wurde in https://github.com/hitobito/hitobito_sww/issues/144 bereits konzipiert.

Abgrenzung: Ursprünglich war in diesem Issue auch noch enthalten dass eine Kopfzeile ein-/Ausblendbar gemacht werden soll. Da eine Kopfzeile in Hitobito bisher noch nicht existiert und zuerst konzeptioniert und entwickelt werden müsste, wird dies von diesem Issue abgegrenzt und gegebenenfalls in einem separaten Issue umgesetzt.

# Mockup

![grafik](https://github.com/hitobito/hitobito_sww/assets/100761305/9fe25839-240e-49aa-b488-69a09f3ec14b)

# Tech-Spec

- Umsetzung im SWW Wagon, sonst öffnen wir die Türen für endlose custom Layouts der Rechnungen. Die Rechnungsfunktion in hitobito Core von Haus aus sollte mehr oder weniger eine gute Basis-Lösung bieten, nicht 100% aller Eventualitäten aller Verbände abdecken. Für vollständige Customization müssen wir auf Wagon-Features oder Tools ausserhalb von hitobito verweisen.

# ToDo

- [x] SWW-Wagon: Neues Tab in den Rechnungseinstellungen
- [x] Auf dem Tab eine Einstellung, um die Linien auf dem Einzahlungsschein auszublenden (default: eingeblendet)
- [x] Im SWW-Wagon die Methode [separators](https://github.com/hitobito/hitobito/blob/master/app/domain/export/pdf/invoice/payment_slip_qr.rb#L47) überschreiben, und auf die neue Einstellung reagieren
- [x] Specs schreiben, dass das Layout der Rechnung nicht verändert wird (die Platzierung der Einzahlungsschein-Elemente sollte exakt gleich bleiben, egal ob die Linien aktiviert oder deaktiviert sind)
