### ISSUE TITLE
Rechnungen nach Zahlungsdatum sortieren

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#147]
Als Kassier will ich die Rechnungen nach dem letzten Zahlungseingang sortieren können. Dadurch erhalte ich eine rasche Übersicht über sämtliche Zahlungen welche in den letzten Tagen eingegangen sind.

Neu soll es auf der Rechnungsübersicht eine zusätzliche Spalte geben welche das Datum der letzten Zahlung auf dieser Rechnung anzeigt.
Die Spalte soll sortiert werden können nach "neuste" zuerst und "älteste" zuerst (analog "Gestellt am" und "Fällig am").
Die neue Spalte "Letzte Zahlung am" kommt zwischen "Fällig am" und "Bezahlt"

![grafik](https://github.com/hitobito/hitobito_sww/assets/100761305/b0a88a9f-74e8-44fa-b57c-de96ce32ec69)

- Hat eine Rechnung mehrere Zahlungen wird nur das Datum der letzten Zahlung angezeigt.

**Offene Fragen**
- ~~Eine Rechnung kann mehrere Zahlungen haben. Welches Datum soll dann genommen werden? Letzte eingegangene Zahlung? (wir gehen davon aus, dass es immer das letzte Zahlungsdatum nehmen soll - Feld benennen als: Letzte Zahlung am)~~
- ~~Was ist mit Issue https://github.com/hitobito/hitobito_sww/issues/58?~~
- ~~Im Issue https://github.com/hitobito/hitobito/issues/1494 wird eine neue Zahlungstabelle erstellt. Würde diese nicht bereits genügen für die Bedürfnisse von SWW?~~

# Tech-Spec

- Möglichkeit, nach Zahlungseingang zu sortieren
- Bei mehreren Zahlungen soll die letzte/neueste Zahlung gelten
- Die neue Spalte "Letzte Zahlung am" kommt zwischen "Fällig am" und "Bezahlt"
- Es soll nur ein Zahlungsdatum in dieser Spalte angezeigt werden, um die Sortierung nachvollziehbar zu halten.

# ToDo

- [x] Partial `invoices/table` anpassen
- [x] `InvoiceController.sort_mappings` erweitern
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

## ungeplant

- [x] Invoice-Views in Gruppen-Sheet anzeigen
- [x] Invoice-Model erweitern, um die Sortierung zu ermöglichen 
- [x] Sortierung nach "Bezahlt" reparieren/ermöglichen
