### ISSUE TITLE
Zahlungseingänge zurückbuchen

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#151]
Rückbuchungen (z.B. doppelt bezahlte Rechnung) können auf der Rechnung nicht angegeben werden. Da Status "bezahlt", kann kein neuer Zahlungseingang (z.B. CHF -20) erfasst werden. Die Rechnung hat aber das (Bsp.) doppelte Total, auch im Buchungsbeleg.

* Der Button "Zahlung erstellen" wird bei Rechnungen mit Status bezahlt weiterhin angezeigt und es können weitere Zahlungen erfast werden.
* Bei Zahlungen mit Status Bezahlt erscheint eine Flash message als Warnhinweis, dass dies e Rechnung bereits den Status bezahlt hat.
* Fällt durch die Rückbuchung der bezahlte Betrag unter den Rechnungsbetrag wird der Status der Rechnung von "Bezahlt" auf den vorher vorhandenen Status zurückgesetzt.
  * Gemäss meinen Tests gibt es keinen Status "Teilbezahlt" in Hitobito. Entsprechend müsste der Status wieder "Gestellt" oder "per Mail versendet" geändert werden.
* Umsetzung nur im SWW Wagon

Frage:
* ~~Was wäre hier das gewünschte Verhalten. Sollen nachdem ein Beleg den Status "Bezahlt" hat, weiterhin Bezahlungen darauf erfasst werden können?~~  -> Ja 
* ~~Wenn nach derRückbuchung der Betrag wieder unter den Rechnungsbetrag fällt, muss dann der Status sich auch auf Teilbezahlt oder offen ändern?~~ -> Ja

# Tech-Spec

- Rückzahlungen sollen erfasst werden können
- Zahlungen sollen daher allgemein erfasst werden können, unabhängig wieviel bereits gezahlt wurde
- Der EBICS-Zahlungsimport sollte solche Zahlungen behandeln können

# ToDo

- [x] `Invoice#payable?` anpassen, um auch bei vollständiger Bezahlung noch Zahlungen erfassen zu können
- [x] `Payment#update_invoice` anpassen, um auch wieder "nicht bezahlt" zu werden
- [x] `Payment::EbicsImportJob` sollte Zahlungen korrekt zuordnen können (oder ignorieren)
- [x] Specs schreiben
- [x] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
