### ISSUE TITLE
PEOPLE: Neue Attribute Person

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#16]
Im SWW Wagon sollen folgende Custom Attribute auf der Person erstellt werden:

- **alabus_id**, string, null: true, unique: true
  - wird im UI nicht angezeigt
  - readonly attribut
  - dient als Identifikator für weitere Imports aus Alabus (z.B. Rechnungen)
- **member_number** (Mitglieder-Nummer), :integer, unique: false, null: false, attr_readonly
  - für neue Entries wird dieser Wert automatisch inkrementiert (Loïc gibt noch Bescheid ab welchem Wert wir starten können, soll höher sein als alle bereits vorhandenen Einträge (Import)), wir nehmen mal 100'000 als Startwert an
  - kann nicht manuell erfasst/editiert werden
- **custom_salutation** (Benutzerdefinierte Anrede), :string, null: true
- **magazin_abo_number** (Abonummer Magazin): :string, null: true
- **language**: https://github.com/hitobito/hitobito/issues/1663

# ToDo

- [x] DB Migration mit neuen Attributen erstellen
- [x] übersetzung DE für Attribute
- [x] Autoinkrement für member_number implementieren

**Comment by mtnstar** [comment]
branch feature/16_person_attributes
