### ISSUE TITLE
PEOPLE: CSV Import Personendaten FOs

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#17]
für den einmaligen Import pro Fachorganisation (FO) der Personendaten aus Alabus soll ein automatisierter Import gebaut werden.

Es gibt ungefähr 17 Fachorganisationen und dieser Import wird pro FO einmalig angewendet.

Alabus Daten liegen als Excel-Export vor. Export kann vor dem Import manuell in ein CSV umgewandelt werden.

Dieser Import ergänzt den Import Dachverband: #14 

Als Parameter wird die Gruppen ID der Mitgliedergruppe (Type Group::Mitglieder) in welche die Personen importiert werden sollen angegeben. Alle Personen erhalten die Rolle Aktivmitglied

Zusätzliche Import-Felder:

| Alabus Attribut                        | Inhalt                                       | Hitobito Attribut                                                                                   |
|----------------------------------------|----------------------------------------------|-----------------------------------------------------------------------------------------------------|
| id (genauen Name klären)                              | Unique Alabus Personen ID | wird verwendet um die Person in Hitobito zu assignen (person#alabus_id)    |
| Abo1End                                | Abo Ende d.o.                                | Rolle Group::Mitglieder::MagazinAbonnent, :deleted_at                                                                  |
| Abo1Number                             | Abonummer Magazin                     | Person#magazin_abo_number  #16                                                    |
| Abo1                                | Print-Abo, Kombi-Abo                           |   Tag auf Person abo:print, abo:kombi                                                                                                  |
|PrimaryCategory                   | Einzel, Doppelmitglied | category:Einzel, category:Doppelmitglied | 
| MemberEntryDate                        | Eintrittsdatum                               | Aktivmitglied#created_at                                                                  |
| MemberExitDate                         | Austrittsdatum                               | Aktivmitglied#deleted_at                                                                    |
| PrimaryCommChannel |                                              | Tag Newsletter falls Wert Newsletter in Exportspalte                                                                            |
| NameAddOn                              | weitere Person im gleichen Haushalt          | Neues Attribut auf Person#name_add_on, string, null: true,  |
| Title                              | Titel Person         | neues Attribut title auf Person |
| PrimaryAddressCountryLICTranslated      | Land z.B. Schweiz, immer deutsche Bezeichnung       | person#country, default: CH|

# Tech-Spec

- Basiert auf #14
- [x] rails import:people_fo
  - [x] source datei: $WAGON_ROOT/db/seeds/production/people_fo.csv
  - [x] parameter group_id
- [x] rename import:people to import:people_sww (damit klar unterschieden wird)
  - [x] source datei: $WAGON_ROOT/db/seeds/production/people_sww.csv
  - [x] Anpassen im SWW Wagon von #format_tag_category damit tag prefix 'category' sowie 'abo' übersetzt wird
    - [x] https://github.com/hitobito/hitobito/blob/master/app/helpers/tag_lists_helper.rb#L13.
    - [x] z.B. für Wert category:Einzelmitglied wird Kategorie:Einzelmitglied angezeigt falls UI-Sprache DE
    - [x] übersetzung in locale file
- [x] Zusätzliches Attribut person#title, :string, null: true,
  - [x] Editierbar
  - [x] Positioniert nach Name, Vorname im UI
  - [x] wird in allen Personenexport mitexportiert
- [x] Zusätzliches Attribut person#name_add_on, :string, null: true
  - [x] Editierbar
  - [x] Namenszusatz
  - [x] Positioniert nach title im UI
  - [x] wird in allen Personenexport mitexportiert
- [x] Neue Rolle Group::Mitglieder::MagazinAbonnent
  - [x] Role Model: created_at, deleted_at berücksichtigen/editierbar machen analog https://github.com/hitobito/hitobito_sbv/blob/master/app/models/sbv/role.rb
  - [x] dies dient dazu die Dauer z.B. von Magazin Abonnenten einzuschränken
  - [x] übersetzung von/bis (created_at, deleted_at)
- [x] Es kann vorkommen das eine E-Mail Adresse in mehreren FO exports vorhanden ist.
  - [x] Falls eine email bereits als haupt-email vergeben ist, bei der aktuell zu importierenden person die hautp-email leer lassen und nur eine zusätzliche e-mail erstellen. Die Haupt-email ist unique und wird als login verwendet.
   - [x] Leider können wir die beiden Personeneinträge mit gleicher E-Mail nicht zusammenmergen und verschiedene Rollen der gleichen Person assignen. Es darf nicht ersichtlich sein das eine Person in einer anderen FO Mitglied ist (auflistung rollen)

# ToDo

**Comment by kebpot** [comment]
<p dir="auto">Es gibt ungefähr **17** Fachorganisationen und dieser Import wird pro FO einmalig angewendet.</p>
<p dir="auto">Als Parameter wird die Gruppen ID der Mitgliedergruppe 
(Type Group::Mitglieder) in welche die Personen importiert werden sollen
 angegeben. Alle Personen erhalten die Rolle Aktivmitglied **Personen welche bei MemberExitDate einen Entrag haben sollte die Rolle Aktivmitglied ab Datum deaktiviert werden - Person aber trotzdem in Hitobito behalten**
<p dir="auto">Zusätzliche Import-Felder:</p>


Alabus Attribut | Inhalt | Hitobito Attribut
-- | -- | --
Abo1Start | Abo Seit von wandern.ch (**physisches Print/Kombi Magazin**) | Rolle Group::Mitglieder::AboMagazin, created_at
Abo1End | Abo Ende d.o. | Rolle Group::Mitglieder::AbonnentMagazin, :deleted_at
Abo1Number | Abonummer Magazin | Person#magazin_abo_number  #16
Abotyp1 | Printabo, Kombiabo | Tag auf Person abo:print, abo:kombi
PrimaryCategory | Einzel, Doppelmitglied | category:Einzel, category:Doppelmitglied
MemberEntryDate | Eintrittsdatum | Aktivmitglied#created_at
MemberExitDate | Austrittsdatum | Aktivmitglied#deleted_at
PrimaryCommunication |   | Tag Newsletter falls Wert Newsletter in Exportspalte
NameAddOn | weitere Person im gleichen Haushalt **oder Abteilung, Rechnungsinfo, etc.** | **nichts machen, Wert in Feld wiedergeben aber keine neue Person erfassen. Daten nicht oin allen FO gleich**
Title | Titel Person | neues Attribut title auf Person
**Land | Land Person | neues Attribut Land auf Person, Standard Schweiz**
