### ISSUE TITLE
Mehr als 50 Rechnungen auf einmal auf gestellt/gemahnt setzen

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#172]
Wir würden gerne mehr als 50 Rechnungen (1 Seite) von Rechnungen innerhalb einer Sammelrechnung auf einmal stellen/mahnen können. Aktuell wählen wir bei einer Sammelrechnung auf jeder Seite (z.B. bei 600 Rechnungen 12x) mittels der Checkbox alle Rechnungen auf der Seite aus und wiederholen den Prozess pro Seite. Das ist etwas umständlich, vor allem bei grossen Rechnungsversänden.

![Sammelrechnungen_Rechnung-stellen_pro-Seite](https://github.com/hitobito/hitobito_sww/assets/124251904/45666796-d305-4cd3-be74-9fbd76a11e69)

Wenn möglich/sinnvoll, wäre es von uns gewünscht, dass nach Öffnen einer Sammelrechnung ohne das Anwählen einer Rechnung alle im aktuellen Filter geändert werden.

Beispiel: Ich generiere eine Sammelrechnung mit 600 Rechnungen. Ich öffne die Sammelrechnung und klicke auf "Status setzen Gestellt/Gemahnt".  Alle Rechnungen in dieser Sammelrechnung werden gestellt. Nach zwei Monaten möchte ich die Mahnungen generieren. Ich filtere nach Status "Gestellt" und erhalte 150 Rechnungen. Ich wähle keine einzelnen Einträge an und klicke auf "Status setzen Gestellt/Gemahnt". Alle offenen/gefilterten Rechnungen in dieser Sammelrechnung/Ansicht werden gemahnt.

# Tech-Spec

- alle Rechnung im aktuellen Filter gleichzeitig bearbeiten
- Die Rechnungen werden aus Performance-Gründen seitenweise angezeigt
- Es sollten nicht mehrere UI-Elemente sichtbar sein
- Die Anzahl der zu bearbeitenden Elemente sollte sichtbar sein
- Ablauf ähnlich wie Github Notifications

# ToDo

- [x] Anzahl der gewählten Elemente anzeigen
- [x] Anzeigen können, wieviele Elemente "alle Elemente" sind
- [x] Toggle einbauen (kann ein Link sein), der von den sichtbaren auf alle Elemente umschaltet
- [x] Controller erweitern, dass alle Elemente einer Liste bearbeitet werden
- [x] Wenn die Checkbox deaktiviert wird, werden keine Elemente selektiert
- [x] Nach dem deaktivieren selektiert die Checkbox wieder nur die sichtbaren Elemente (und zeigt den Umschaltlink an)
- [x] Umschaltlink nur anzeigen, wenn mehr Elemente vorhanden sind, als angezeigt werden können
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by ThomasEllenberger** [comment]
Dies ist ein verhalten, welches wir gerne im Core von Hitobito ändern wollen.

Es soll möglich sein bei sämtlichen Rechungen einer Sammelrechnung den Status auf Einmal zu ändern.

Bitte beim Refinen dieses Issues überlegen/abklären/mit mir diskutieren, wie dieses Ziel am sinnvollsten erreicht werden kann.
Im Gegensatz zur Anforderung im originalen Ticket bin ich der Meinung dass es besser wäre, wenn man noch eine Checkbox anwählen muss um anschliessend den Status für alle Rechnungen zu ändern.
Ist es intuitiv, wenn die Checkbox oberhalb der ersten Rechnung einfach Alle Rechnungen auswähl, und nicht nur die angezeigten ersten 50...?

**Comment by diegosteiner** [comment]
Erster Wurf sieht so aus:

![Screencast From 2024-12-20 14-33-16 mp4](https://github.com/user-attachments/assets/92d39047-eca6-431d-afc3-760c7d7f02c8)

**Comment by nchiapol** [comment]
@ThomasEllenberger In der Cevi-Integration funktioniert das ebenfalls, hat allerdings zwei "Unschönheiten" (vgl. Screenshot), die im Screencast von Diego nicht vorhanden sind:
  * der Link "Alle ... auswählen" wird mit einer falschen Schriftgrösse und nicht korrekt ausgerichtet angezeigt
  * der Link wird bereits angezeigt, wenn nur eine Person ausgewählt wurde - er funktioniert in dem Moment aber nicht. Ein Klick darauf hat keinen Effekt.

![Image](https://github.com/user-attachments/assets/a1b396fe-249b-4bfe-8bf5-ffd92c15138a)

**Comment by ThomasEllenberger** [comment]
@nchiapol Dieses Issue hat aktuell noch weitere Probleme (Es scheint bei mehr als 10 Seiten nicht mehr zu funktionieren).
@kronn Ist hier noch dran, gerne gebe ich deine Inputs auch noch an ihn weiter.
