### ISSUE TITLE
Originalrechnung nach Mahnung erneut generieren können

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#173]
# Ausgangslage
Nachdem eine Rechnung auf Status "gemahnt" gestellt wurde, kann auf die Originalrechnung nicht mehr zugegriffen werden. Der Status der Rechnung kann auch nicht zurückgestellt werden. Als Workaround erstellen wir aktuell eine neue Rechnung und lassen diese im Status "Entwurf", drucken sie und stornieren sie dann nach dem Versand wieder.

Wir würden das gerne optimieren, indem irgendwie auf die Originalrechnung zugegriffen werden kann oder ggf. der Status der Rechnung zurückgestellt werden kann.

# Anforderungen
- Beim Drucken einer Rechnung soll eine zusätzliche Option vorhanden sein. Diese soll immer die Rechnung drucken wie sie existierte zum Zeitpunkt an dem der Status der Rechnung auf "gestellt" geändert wurde.

# Mockup

![Image](https://github.com/user-attachments/assets/d9753772-910d-486e-92af-6463a860cbcd)

# Tech-Spec

- erneutes Drucken einer Rechnung
- alle Daten in der Rechnung sollen gleich bleiben
- der Status der Invoice soll in der DB nicht geändert werden
- Umsetzung im Core

# ToDo

- Model/View/Controller anpassen
    - [x] `Dropdown::Invoices#pdf_links`
    - [x] `InvoicesController#show(format: :pdf)`
- Specs schreiben
    - [x] Links vorhanden
    - [x] Rechnungs-PDF wird mit alten Daten neu erzeugt
- [x] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] [DoD](https://github.com/hitobito/hitobito/blob/master/doc/developer/process/definition_of_done.md) geprüft und erfüllt?
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by ThomasEllenberger** [comment]
Konnte auf Integration erfolgreich getestet werden.
