### ISSUE TITLE
Bei Mahnungserstellung die Anzeige des Rechungstexts optional machen

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#174]
Wenn eine Rechnung auf Status "gemahnt" gesetzt wird, wird der Mahntext der entsprechenden Stufe unten an den Rechnungstext angefügt. Wir würden an dieser Stelle gerne auf den Rechnungstext verzichten, da der Text meistens viel zu lang wird und auch im Kontext zum Mahntext oft keinen Sinn mehr gibt.

Aktuell löschen wir den Rechnungstext bei jeder Mahnung manuell heraus.

![Mahnung_Text](https://github.com/hitobito/hitobito_sww/assets/124251904/f7407c36-2089-4644-99bd-363cb0088cd0)

# Tech-Spec

- Ermöglichen, dass die Mahnung bereits der komplette Text ist
- Der aktuelle Zustand muss der Default bleiben
- Neue Checkbox "Ursprünglichen Rechnungstext vor Mahnungstext anzeigen" mit default "true" hinzufügen
- Umsetzung im Core

# ToDo

- [x] Migration erstellen
    - `PaymentReminderConfig#show_invoice_description` als boolean, default true, not null
- [x] `Export::Pdf::Invoice::Articles#render` anpassen
- [x] `InvoiceConfigsController` um neues Attribut erweitern
- [x] `app/views/invoice_configs/_reminder_fields.html.haml` erweitern
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by ThomasEllenberger** [comment]
Die PPS hat das gleiche Anliegen. 
Umsetzung im Core prüfen

**Comment by diegosteiner** [comment]
PR im core: https://github.com/hitobito/hitobito/pull/3071
PR im sww: https://github.com/hitobito/hitobito_sww/pull/222
