### ISSUE TITLE
EVENT: Register "Anmeldungen" fehlt

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#183]
### User Story

Als Leitung eines Gremiums möchte ich bei Anlässen in meinem Gremium in jedem Fall auch die Anmeldungen und die Warteliste von allen Events sehen und bearbeiten können, unabhängig von meiner Rolle auf dem Anlass (auch wenn ich keine Rolle im jeweiligen Anlass habe)

### Aktuelles Verhalten

Als "Leitung" (Rolle) eines Gremium/Projektgruppe (Gruppe) kann ich Anlässe sehen und bearbeiten. Das Tab "Anmeldungen" ist jedoch nicht verfügbar. Alle anderen (Info/Teilnehmende/Einladungen) kann ich sehen.
Die Rolle "Leitung" im Gruppentyp "Gremium" hat die Berechtigung [:group_and_below_full].

### Gewünschtes Verhalten

Als "Leitung" (Rolle) eines Gremium/Projektgruppe (Gruppe) kann ich Anlässe sehen und bearbeiten. Ich kann auf alle Register zugreifen (Info/Teilnehmende/Anmeldungen/Einladungen) und so auch die Warteliste verwalten.

### Schritte zu reproduzieren

1. Gruppe "Gremium/Projektgruppe" erstellen
2. Person mit Rolle "Leitung" hinzufügen
3. Anlass erstellen
4. Person mit Rolle Leitung imitieren und auf Anlass navigieren

### Testcase:

Person https://sww.puzzle.ch/de/groups/268/people/55827 kann in Anlass https://sww.puzzle.ch/de/groups/268/events/38 das Tab Anmeldungen nicht sehen

### ToDo

- Ability `:application_market` wird benötigt
- Anlässe haben beim SWW Anmeldungen

- [x] `EventAbility` erweitern, sodass die Permission `:group_and_below_full` auch die Ability `:application_market` erhält.
- [x] :warning: auch allen bisherigen Abilities aufführen
- [x] Specs schreiben
- [x] mit obiger Rolle testen
- [x] im CHANGELOG unter unreleased hinzufügen
