### ISSUE TITLE
EVENT: Mailabsender individualisieren

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#195]
# Ausgangslage
Für alle E-Mails, welche beim Verwalten von einem Anlass ausgelöst werden (Anmeldungen, Abmeldungen, Voranmeldungen, ...) soll analog dem Rechnungsversand ein individueller Anzeigename pro Gruppe definiert werden können.

# Anforderungen
- Email pro Gruppe definierbar.
  - Vorschlag: Auf Gruppen-Info einen neuen Reiter "E-Mail" hinzufügen
  - Wenn in der Gruppe kein Absendername vorhanden ist, gilt der Absendername auf dem Layer als Fallback
- Sämtliche E-Mails rund um Anlässe werden mit dieser Mail als Absender versendet.
   - Anlass: E-Mail Abmeldebestätigung
   - Anlass: E-Mail Anmeldebestätigung
   - Anlass: E-Mail Freigabe der Anmeldung
   - Anlass: E-Mail Teilnehmer-/in hat sich angemeldet
   - Anlass: E-Mail Voranmeldung
   - Anlass: Temporäres Login senden

# Mockups

![Image](https://github.com/user-attachments/assets/fb2ed895-9314-4193-97ec-2c784fe92afe)

![Image](https://github.com/user-attachments/assets/4cc7987d-244b-4780-af0c-8115cc939c1f)

# ToDo

- [x] Core vorbereiten
- [x] Wagon anpassen
- [x] Specs core
- [x] Specs wagon
- [x] Mit angemessener Rolle "durchklicken"
- [x] [DoD](https://github.com/hitobito/hitobito/blob/master/doc/developer/process/definition_of_done.md) geprüft und erfüllt?
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
