### ISSUE TITLE
INVOICE: Mehrsprachigkeit Rechnungseinstellungen > Mahnungen

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#198]
# Ausgangslage
Als Rechnungssteller eines mehrsprachigen Kantons möchte ich meine Mahntexte in den Rechnungseinstellungen pro Sprache (aktuell deutsch und französisch) hinterlegen können, um diese nicht pro Versand anpassen zu müssen.

![image](https://github.com/user-attachments/assets/b49046cd-40d7-4bf5-bdda-9a4e2ee06d5e)

# Anforderung
- Mahntexte sollen in allen von der jeweiligen Umgebung suporteten Sprachen hinterlegt werden können.
- Wird eine Mahnung ausgelöst soll diese automatisch in der Sprache der zu mahnenden Person versendet werden (Falls vorhanden - Fallback: andere ausgefüllte Sprache)
- Evtl. Grundsatzdiskussion wie wir in Hitobito zukünftig mehrsprachige Felder übersetzen wollen. Das ändern der gesamten Sprache um ein Feld in einer anderen Sprache abzufüllen ist nicht sehr intuitiv.

# Tech-Spec

- Mahnungen in mehrere Sprache erfassen können
- Verwendung der Mahnung in der Sprache des Empfängers
- sauberen Fallback, wenn es nicht in der Sprache des Empfängers vorhanden ist
- Fallback-Regeln siehe `Rails.application.config.i18n.fallbacks`

# ToDo

- Migration erstellen
  - [x] globalize payment_reminder_configs
- Model/View/Controller anpassen
  - [x] PaymentReminderConfig.include Globalized
  - [x] PaymentReminderConfig.translates :title, :text
  - [x] ggf. Controller/Views anpassen, um locale richtig zu setzen
- Specs schreiben
  - [x] Fallback, wenn nur eine Sprache eingetragen ist
  - [x] Fallback, wenn gewählte Sprache nicht eingetragen
  - [x] Update in anderen Sprachen
- [x] Mit angemessener Rolle "durchklicken"
- [x] [DoD](https://github.com/hitobito/hitobito/blob/master/doc/developer/process/definition_of_done.md) geprüft und erfüllt?
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
