### ISSUE TITLE
TECH: Setup der Integrationsumgebung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#2]
Domain: sww.puzzle.ch

Setup erfolgt noch auf Openshift 3 (für Openshift 4 gibt es noch zu viele offene Fragen/Punkte)

# ToDo

- [x] Openshift-Projekt
- [x] Basic setup mit Secrets
- [x] kustomize-overlay
- [x] mailtrap
- [x] dns (sww.puzzle.ch)
- [x] composition-repo
- [x] apply-config
- [x] jenkins-job
- [x] Credentials im Cryptopus
- [x] Github Actions

See: #1

**Comment by kronn** [comment]
LGTM
