### ISSUE TITLE
INVOICE: Mahnung beinhaltet Rechnungsdatum der Originalrechnung

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#200]
Bei der Erstellung einer Mahnung oder Zahlungserinnerung wird, wenn ein "Gestellt am" Datum ausgefüllt ist, immer dieses Datum aufgedruckt. Bei einer Mahnung müsste das heutige Datum aufgedruckt werden.

Rechnung:
![image](https://github.com/user-attachments/assets/d1abb58d-3202-4277-92d5-129e55bc082b)

Mahnung gestellt am:
![image](https://github.com/user-attachments/assets/f26e5681-3b35-4418-82cf-c119237527ee)

Drucken > PDF Mahnung:
![image](https://github.com/user-attachments/assets/f2173e91-65bc-465c-9aaf-a777d7f9232a)

# ToDo

- ~~[ ] Migration erstellen~~
    - add_column :payment_reminders, :sent_at, :date, null: false
- [x] PDF-Export anpassen, das ~~sent_at~~ created_at der Mahnung zu verwenden
- ~~[ ] View~~
    - Formularfeld hinzufügen, default: "heute"
- ~~[ ] Controller~~
    - permitted_attrs anpassen
- [x] Specs schreiben
- [x] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by amaierhofer** [comment]
Bitte noch specs für core und wagon changes ergänzen

**Comment by njaeggi** [comment]
@amaierhofer specs für wagon habe ich im kommentar verlinkt, core specs habe ich bereits ergänzt
