### ISSUE TITLE
PEOPLE: "Login schicken" Sprache

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#203]
Als Support-Person möchte ich Kundinnen oder Kunden das Login per E-Mail schicken können. Aktuell wird die E-Mail immer in der aktuellen Sprache der Support-Person versenden.

![image](https://github.com/user-attachments/assets/257f6923-7481-43fc-b2d3-144b30caa3cf)

# Tech-Spec

- Zielperson besser ansprechen
- Verwirrungen reduzieren

# ToDo

- [x] Person::SendLoginJob anpassen, dass die `@locale` auf `recipient.language` gesetzt wird
- [x] BaseJob#set_locale einen Block mit Zielsprache übergeben können
- [x] Default, wenn Zielsprache nicht gesetzt ist
- [x] Specs schreiben
- [x] Mit angemessenen Rollen (und mehreren Sprachen) "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by ThomasEllenberger** [comment]
Erfolgreich getestet
