### ISSUE TITLE
EVENT: Liste Teilnehmende PDF-Export

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#205]
In einem Anlass unter Teilnehmende > Export > PDF möchten wir gerne folgende Anpassungen:

- Der Titel ist aktuell der Name der Untergruppe. Gewünscht ist der Titel/Name des Anlasses.
- Der Export wird aktuell alphabetisch nach Nachname sortiert. Die Namen sind jedoch mit "Vorname Nachname" aufgeführt. Die Sortierung nach Nachname behalten wir gerne bei. Die Namen sollen jedoch "Nachname Vorname" aufgeführt sein. 
- Der Export wird aktuell im gleichen Tab geöffnet. Wenn möglich, würden wir den Export gerne in einem neuen Tab öffnen lassen.
- Auf dem Export gerne die Rolle der Person aufführen, damit wir unterscheiden können, ob jemand als Teilnehmender oder als Leitungsperson am Anlass dabei ist. Alternativ wäre für uns hier auch eine Auftrennung/Gruppierung möglich (Alle mit Rolle "Teilnehmer" in einer Liste und eine zweite Liste mit allen anderen Rollen, dazwischen einfach ein Abstand und/oder Zwischentitel).

# ToDo

- [x] Titel: Anlass (SWW Wagon)
- [x] Namen als "Nachname Vorname" darstellen (Core)
- [x] Export in neuem Tab öffnen `target: '_blank'` (Core)
- [x] Eventrollen als Spalte hinzufügen (SWW Wagon)

**Comment by ThomasEllenberger** [comment]
Erfolgreich getestet.
