### ISSUE TITLE
EVENT: Anmeldemaske

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#207]
Bei der Anmeldung an einen Anlass, möchten wir gerne:

- Link zur externen Anmeldung ausblenden
Die anmeldende Person befindet sich bereits auf dem Link zur externen Anmeldung und dreht sich so im Kreis
![image](https://github.com/user-attachments/assets/816c154b-cba4-4013-a65e-913831670b55)

- Wenn der Anmeldeschluss des Anlasses bereits in der Vergangenheit ist, soll auf der Anmeldemaske ein entsprechender Hinweis ausgegeben werden.
- Wenn der Anlass ausgebucht ist und keine Warteliste aktiv ist, soll auf der Anmeldemaske ein entsprechender Hinweis ausgegeben werden.

- Das Icon vor "Anmelden" würden wir gerne austauschen. Diese hier sieht einem Gutzeichen ähnlich und verwirrt so gewisse Anmeldende, weil es so aussieht, als wäre die Anmeldung bereits erfolgt. Gegebenenfalls könnte ein simpler Pfeil nach rechts oder ein + Zeichen gewählt werden.
![image](https://github.com/user-attachments/assets/0ab05943-081a-44ab-8bf7-62b7553b5d73)

# Tech-Spec

- weniger Verwirrung
- mehr Informationen zum Status
- eindeutige Symbolsprache

# ToDo

- [x] Link zur externen Anmeldung von der Anmeldeseite entfernen
- [x] Hinweis, wenn Anmeldeschluss bereits vorbei ist
- [x] Hinweis, wenn Anlass (ohne Warteliste) ausgebucht ist.
- [x] Icon für Anmeldung auf "plus" oder anderes sinnvolles Icon wechseln.
- [x] Abmelde-Icon als konsistentes Gegenstück zum Anmelden auswählen.
- [x] Specs, zumindest für Hinweise und Link, schreiben
- [x] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
