### ISSUE TITLE
INVOICE: Anzeige Titel & Empfängergruppe Sammelrechnung

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#209]
Auf der Übersicht meiner Sammelrechnungen im aktuellen Jahr sind die Spalten Titel, Empfänger, Empfänger Insgesamt, Empfänger bezahlt, Betrag insgesamt und Betrag bezahlt verfügbar. Wenn eine Sammelrechnung geöffnet wird, zeigt es nur noch den Titel an.
Wir würden hier den Titel gerne mit dem "Empfänger" erweitern, damit auch immer gleich klar ist, welche Rechnung geöffnet ist.

Übersicht:
![365171528-2e9d9e53-a8f0-4e67-b7f5-34bc221afe8e](https://github.com/user-attachments/assets/9f19bbf0-f9f5-40e1-b380-b486c92bc87b)

Detail aktuell:
![365171670-d1fa2e66-2b79-4ec0-af1d-19ac87d2a2b0](https://github.com/user-attachments/assets/7703984c-4d03-4d5a-9835-6bd6dc8bdc9e)

Detail gewünscht (zum Beispiel):
![365171915-e746c32d-bc9f-4039-8e47-69350199654c](https://github.com/user-attachments/assets/b5540caa-9907-4e55-9576-68627c7794eb)

# ToDo

- [ ] Korrekte ivar im Controller setzen
- [ ] Sheet::Invoice sollte das Rendering übernehmen
- [ ] durchklicken
- [ ] [DoD](https://github.com/hitobito/hitobito/blob/master/doc/developer/process/definition_of_done.md) geprüft und erfüllt?
