### ISSUE TITLE
EXPORT: Mitgliedernummer aller Personen im selben Haushalt

### ISSUE THREAD

**Issue by thaeuselmann** [hitobito/hitobito_sww#212]
Neu soll zusätzlich auf dem Excel/CSV Personenexport "Alle Angaben" je auch die Mitgliedernummern aller anderen Personen im Haushalt in einer separaten Spalte aufgeführt werden.

~ggf. gemeinsam mit https://github.com/hitobito/hitobito_sww/issues/186 anschauen~

# ToDo

- [ ] Mitgliedernummer als Spalte pro Person hinzufügen
- [ ] Export::Tabular::People#person_attributes im Wagon erweitern
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] [DoD](https://github.com/hitobito/hitobito/blob/master/doc/developer/process/definition_of_done.md) geprüft und erfüllt?
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by njaeggi** [comment]
Mit @ThomasEllenberger besprochen, aktuell im Export "Alle Angaben" mit zusaätzlicher Spalte "Mitgliedernummern Haushaltsmitglieder" umgesetzt. Nummern werden kommasepariert aufgelistet. 

@ThomasEllenberger wird genaue Umstände noch abklären.

**Comment by ThomasEllenberger** [comment]
Erfolgreich getestet.
Der Export "Alle Angaben" hat nun eine zusätzliche Spalte "Mitgliedernummern Haushaltmitglieder" in welcher die Mitgliedernummern aller anderen Personen im Gleichen Haushalt kommagetrennt aufgeführt werden.
