### ISSUE TITLE
Staging: Regelmässiger Datensync & Regelmässige Releases

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sww#215]
Die SWW Staging Umgebung soll zukünftig immer die gleiche Version und den gleichen Datenstand haben wie die Produktivumgebung vom SWW.

In Issue https://github.com/hitobito/hitobito_sww/issues/214 wurde die Umgebung einmalig auf den neusten Stand gebracht.
Zukünftig soll die Staging Umgebung in die Quartalsweisen Releases miteinbezogen werden.
Zudem soll monatlich ein Datensync auf die Staging-Umgebung durchegführt werden. Jeweils am 1. des Monats.Dabei sollen sämtliche Daten der Prod-Datenbank auf die Staging koppiert werden.

# Tech-Spec

- regelmässig aktualisiertes/gereinigtes Abbild der Prod-Daten, um die Integration mit externen Tools zu testen
- ~Login ist dort nicht nötig~ Sämtliche Mitarbeiter der Geschäftsstelle brauchen Zugriff auf die Staging Umgebung
- ~Einzig der Root-User sollte dort noch Zugriff haben~
- nötige Zugriffe (ServiceTokens u.ä.) müssen in der Prod-DB vorhanden sein und werden dann von dort übernommen
- Reset-Interval: Monatlich, am 1. des Monats

# ToDo

- [x] Reset-Interval von 3 Monaten verifizieren und ggf. hier anpassen -> Neu monatlich
- [x] Anpassung des Deployments, dass mit jedem Prod-Release auch ein Staging-Release der gleichen Version stattfindet (siehe composition-repo)
- [x] DB-User so anpassen, dass er die Prod-DB lesen kann
- [x] Sicherstellen, dass keine Mails nach aussen verschickt werden
- [x] Background-Job erstellen, der den Transfer macht
- [x] Dump aus prod-db ziehen
- [x] Dump in staging-db einspielen
- [x] Passwörter von allen Personen ausser `Group.roots.first.people.uniq` leeren
- [x] Background-Job wieder so schedulen, dass er in der neuen DB nach dem Reset-Interval erneut läuft
- [x] Manuell prüfen, dass der Job durchläuft, die DB resettet und nachher wieder geschedulet ist

# PR

Die Umsetzung ist rein im Kubernetes-Cluster, daher: https://gitlab.puzzle.ch/pitc_hit/deployments/hitobito/-/merge_requests/19

**Comment by kronn** [comment]
Aktuell ist der Job so eingestellt, dass er immer Abends am 15. eines Monats läuft. 
( https://crontab.guru/#4_20_15_*_* )

Wenn gewünscht, kann man jederzeit manuell einen Sync laufen lassen.

**Comment by olibrian** [comment]
Gemäss cloudtec wird OAuth Redirect-URL überschrieben. Dies sollte nicht so sein, da sich die SWW Admin User via Staging Webseite an der Staging Hitobito Instanz anmelden. Details im internen Ticket: https://help.puzzle.ch/#ticket/zoom/9024

**Comment by ThomasEllenberger** [comment]
> Gemäss cloudtec wird OAuth Redirect-URL überschrieben. Dies sollte nicht so sein, da sich die SWW Admin User via Staging Webseite an der Staging Hitobito Instanz anmelden. Details im internen Ticket: https://help.puzzle.ch/#ticket/zoom/9024

Dies wurde so konzipiert und mit SWW abgesprochen.
Stand heute gehe ich davon aus dass alles funktioniert wie es sollte, werde mich hier aber erneut mit SWW absprechen.

-> Aktuell keine Arbeiten geplant

**Comment by ThomasEllenberger** [comment]
> > Gemäss cloudtec wird OAuth Redirect-URL überschrieben. Dies sollte nicht so sein, da sich die SWW Admin User via Staging Webseite an der Staging Hitobito Instanz anmelden. Details im internen Ticket: https://help.puzzle.ch/#ticket/zoom/9024
> 
> Dies wurde so konzipiert und mit SWW abgesprochen. Stand heute gehe ich davon aus dass alles funktioniert wie es sollte, werde mich hier aber erneut mit SWW absprechen.
> 
> -> Aktuell keine Arbeiten geplant

Wurde gelöst indem auf Prod das selbe API-Token hinterlegt wurde.
Dadurch wird beim regelmässigen Datensync auch dieses Tocken immer wieder auf der Integration erstellt.

--> closed
