### ISSUE TITLE
PEOPLE: CSV import improvements

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#25]
Für die beiden Imports **people_fo** und **invoices_fo** sollen noch folgende Verbesserungen angebracht werden:

## 1. Auflisten der Einträge/Rows die nicht importiert werden konnten

Am Ende des Import Tasks soll ausgegeben werden wieviele Rows das erfolgreich importiert werden konnten. 3454/3542
Ausserdem soll eine Liste mit den fehlenden Einträgen ausgegeben werden.

## 2. Erneuter Run des Import Tasks

Hat man die fehlenden Einträge gefixt, soll es möglich sein das gleiche CSV mit den korrigierten nochmals zu importieren. Es soll geprüft werden ob ein Eintrag bereits existiert. Als ID wird die alabus_id bzw. bei den Rechnungen die esr als Referenz verwendet. Einträge die noch nicht existieren sollen erstellt werden.

Momentan gibt es side effects wenn man die gleiche Datei ein zweites mal importiert. z.B. werden bei Personen Rollen und Additional E-Mails mehrfach assigned.

## 3. Rechnungsstatus Teilbezahlt

wird ignoriert, nur die mit Status offen importieren wie bereits implementiert.

# ToDo

- [x] Import auf Integration Personen Daten UR, Feedback von Loic
- [x] Falls i.o. Import Personendaten UR auf Produktion, Vorher Prod Releasen
- [ ] Import Rechnungen und Personen Daten LU, Feedback von Loic zu Rechnungsimport
- [x] Implementation inkl. Testing des Reporting für den people_fo import
- [x] Implementation inkl. Testing des Reporting für den invoices_fo import
- [ ] Implementation inkl. Testing re-run people_fo import
- [ ] Implementation inkl. Testing re-run invoices_fo import
- [ ] Testen des Imports mit allen 4 geplanten Imports FOs (LU, NW, GR, UR)
