### ISSUE TITLE
INVOICE: Rechnungen mit Position ohne Total

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#26]
Als Rechnungssteller
möchte ich eine Rechnung erstellen, welche Positionen enthält aber kein Total oder Betrag aufweist,
um dem Rechnungsempfänger offen zu lassen, welchen Betrag er einzahlt.

In diesem speziellen Fall soll kein Total auf der Rechnung und kein Betrag im QR Code angezeigt werden. Alte EZ können vernachlässigt werden

Möglichkeiten zur Umsetzung:

* Beim erstellen der Rechnung wählen ob Total und Rechnungsbetrag angezeigt werden soll oder nicht.

Offen zu klären:

* Soll im System ein Rechnungsbetrag geführt werden oder soll der Rechnungsbetrag im System auch leer sein.
* Explizit definieren als Einstellung auf der Rechnung "Rechnung mit/ohne Totalbetrag"
* Bewusster Entscheid, Rechnung wird unverständlicher, Rechnungsempfänger muss Betrag eingeben.

# Mockup

Beispiel eines PDF:

![Screenshot from 2022-04-04 08-57-32](https://user-images.githubusercontent.com/9592347/161490417-e30f24f0-cd32-4185-b68b-89da2509b054.png)

Update zum Bild: MWSt muss auf dem PDF bleiben.

# Tech-Spec

- Die Rechnung wird als explizit "ohne Total" markiert
- ein hinweisender Rechnungsposten "Spende" ist möglich, aber nicht zwingend
- Spenden sollen so suggeriert und ermöglicht werden
- Der Rechnungsbetrag wird intern weiter gespeichert
- Die Rechnung gilt damit weiter als bezahlt, wenn mindestens der Rechnungsbetrag gezahlt wurde. Spenden/Überzahlungen sind bisher auch schon möglich.
- Eine Rechnung "ohne Total" enthält keine Zwischenbetrag und keinen Gesamtbetrag.
- Die Mehrwertsteuer wird weiterhin angezeigt und bezieht sich (wie bisher) auf die Summe der Rechnungsposten mit Betrag.
- Die QR-Rechnung enthält keinen Betrag.
- Es ergibt sich hiermit kein variabler Spendenaufruf mit pro Empfänger unterschiedlichem Betrag, sondern ein "leerer" Spendenaufruf, der für alle Empfänger gleich ist.
- Es gibt bereits Rechnungen ohne Betrag: https://github.com/hitobito/hitobito_die_mitte/issues/148

# ToDo

- [x] Migration erstellen
	- [x] `add_column :invoices, :hide_total, :boolean, null: false, default: false`
- [x] Domainklassen anpassen
	- [x] `Export::Pdf::Invoice::Articles`
		- [x] Gesamt- und Zwischenbetrag ggf. ausblenden
	- [x] `Export::Pdf::Invoice::PaymentSlipQr`
		- [x] Betrag aus QR-Code ggf. entfernen
	- [x] `Export::Pdf::Invoice::PaymentSlip`
		- [x] Betrag für Codierzeile soll auch leer sein, analog zum QR Code
- [x] Model/View/Controller anpassen
	- [x] Checkbox anzeigen
	- [x] Checkbox in permitted_attrs aufnehmen
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag hinzufügen

**Comment by mtnstar** [comment]
![image](https://user-images.githubusercontent.com/655627/167776798-849e11ef-4cd6-4368-ad88-d477cdf688e2.png)

habe mal versucht mit meinem E-Banking ab den Code zu scannen ... der QR Code aus der lokalen Entwicklungsumgebung scheint ungültigt.

@TheWalkingLeek hast du das getestet? liegt das einfach am lokalen Setup das der QR Code ungültig ist?
