### ISSUE TITLE
INVOICE: Ausgabe von Mitgliederausweis

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#27]
Als Sekretariat
möchte ich für meine Mitglieder ein Mitgliederausweis bedrucken,
um direkt aus Hitobito die Daten verwenden zu können.

Über das Abo den Briefexport anpassen, um ein spezielles PDF zu generieren,
welches auf die Vorlage abgestimmt ist. Dadurch werden die notwendigen Daten
direkt auf das Briefpapier gedruckt.

Als Option zum Briefmodul hinzufügen. Vererbung zum Rechnungsbrief.

Offen zu klären:

- Gibt es zum Mitgliederausweis immer eine Rechnung? -> beides möglich
- Definitive Vorlage (Wordvorlage oder PDF)

# Mockup

Beispiel auf dem Rechnungsbrief:

![image](https://user-images.githubusercontent.com/9592347/162146017-5dceba76-1334-4365-a2c0-3213a5407962.png)

Ausgabe als PDF. Markierte stellen werden im PDF generiert. Andere Texte und Bilder sind auf dem Briefpapier vorbedruckt.
![Mitgliederausweis](https://user-images.githubusercontent.com/9592347/168561208-3124ada6-1ba9-4619-9162-f3e8eb5522d4.png)

# Tech-Spec

- Wiederverwendung des normalen Briefes
- Mitgliederausweis kann mit oder ohne Rechnung versandt werden
- Vorlage beachten, ob auch Kopfzeile ausgeblendet werden muss
- Umsetzung im SWW-Wagon

# ToDo

- [x] Klären, ob Mitgliederausweis nur auf Rechnung erscheint
- [x] Definitive Vorlage klären (Wordvorlage oder PDF)
- [x] Migration erstellen
	- [x] `add_column :messages, :membership_card, :boolean, default: false, null: false`
- [x] Domainklassen anpassen
	- [x] `Export::Pdf::Messages::Letter`
	- [x] `Export::Pdf::Messages::Letter::Header`
- [x] Model/View/Controller anpassen
	- [x] Checkbox hinzufügen
	- [x] Checkbox in permitted_attrs aufnehmen
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag hinzufügen
