### ISSUE TITLE
INVOICE: Textvorlage für Rechnungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#28]
Prüfen: Macht es evtl. Sinn das wir anstatt Rechnungstextvorlagen gleich Rechnungsvorlagen einführen?
Damit könnte man das gleiche Model Invoice benutzen mit Flag template. 
diese Option prüfen und ggf. ein neues Ticket erstellen.

Als Rechnungssteller,
möchte ich beim erstellen von Rechnungen immer wieder auf Textvorlagen zurückgreifen,
um effizient wiederkehrende Rechnungen erstellen zu können.

Unter den Einstellungen kann entsprechende Vorlage erfasst werden. Es können beliebige beliebige Textvorlagen erfasst werden. 
Beim Erstellen der Rechnung können die Textvorlagen entsprechend ausgewählt werden und weiter bearbeitet werden.

# Mockup

Mögliche Umsetzung unter den Rechnungseinstellungen:

![image](https://user-images.githubusercontent.com/9592347/161492355-ea58def0-f590-4ae7-b7f1-f6bd000b0047.png)

-> Name vom Tab neu "Textvorlage"

# Tech-Spec

- Vorlage, um schneller gleichlautende Rechnungen erstellen zu können
- Wenn Vorlagen existieren, dann wird ein Dropdown mit den Vorlagen angeboten.
- Vorlagentext wird per JS eingefügt, ersetzt den aktuellen Rechnungstext und kann danach weiter in der Rechung bearbeitet werden.
- Es können meherer Vorlagen erstellt werden, ähnlich wie bei Anmeldenangaben oder weiteren Telefonnummern.
- Vorerst soll es mit 5 Vorlagen gut funktionieren
- Das Feld "Ohne Total" / "Spende" wird für alle Kunden einheitlich dargestellt. Neu ist dies nach den Rechnungsposten und vor dem Rechnungsbetrag.

# ToDo

- [x] Migration erstellen
	- [x] neue Tabelle `message_templates`
	- [x] `references :layer`
	- [x] `varchar :title, null: false`
	- [x] `text :body`
- [x] Models/Views/Controller anpassen
	- Models
		- [x] `MessageTemplate < ActiveRecord::Base`
		- [x] `InvoiceConfig.has_many :message_templates`
	- Rechnungseinstellungen (Controller, View)
		- [x] neues Tab "Textvorlage" in Rechnungseinstellungen hinzufügen
		- [x] `InvoiceConfigsController#permitted_attrs` erweitern
		- [x] siehe [app/views/events/_application_questions_fields.haml](https://github.com/hitobito/hitobito/blob/master/app/views/events/_application_questions_fields.haml)
		- [x] "weitere Vorlage erstellen" Link
	- neuen Brief erstellen (View)
		- [x] Wenn mehr als 1 Vorlage im Layer vorhanden, Dropdown anzeigen
		- [x] Auswahl überschreibt aktuellen Rechnungstext
		- [x] Ob das Template per AJAX geholt wird oder alle vorhandenen direkt im DOM vorhanden sind, ist offen.
			- [x] testen ob 5 - 10 Templates immer noch in vernüftiger Zeit laden
			- [ ] wenn zu langsam, dann eher per AJAX holen (Controller, View)
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
	- [x] in Firefox testen
	- [x] in Chromium-basiertem Browser testen
- [x] Dokumentation hinzufügen
- [x] CHANGELOG-Eintrag hinzufügen
