### ISSUE TITLE
PEOPLE: Zugriff auf Rechnungen für Support

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#30]
Personen mit der Rolle Support sehen heute die Rechnungen der FOs nicht sondern nur die Rechnungen des Dachverbands. Diese Rolle hat die Berechtigung `[:layer_and_below_full, :admin, :finance, :impersonation]`

Info: Issue enthielt ursprünglich auch noch einen Teil zum anpassen von Abos. Dies wird nun im Issue #94 gelöst.

# TechSpec

- Umsetzung im Wagon
- Support Personen sollen auch die Rechnungen der FOs sehen und verwalten können.

# ToDo

- [x] neue Ability `:complete_finance` einführen, die keine Layerbeschränkung hat
- [x] Dachverband-Support bekommt diese Permission
- [x] Specs gründlich schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
