### ISSUE TITLE
INVOICE: Anpassungen Rechnungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#36]
Für einen dringenden Rechnungslauf braucht es folgende Anpassungen

* Zeile mit der MwSt weg lassen
* Empfänger Adresse links anstelle rechts 
* Export läuft bei 150 Rechnungen in ein Timeout. Kann dies temporär erhöht werden?

Umsetzung im Wagon SWW

## Mockup

![Screenshot from 2022-04-14 22-25-08](https://user-images.githubusercontent.com/9592347/163470336-ff1f92ea-0486-4a2b-8691-2690f5a6f356.png)

## Todo
- [ ] Export::Pdf::Invoice::InvoiceInformation überschreiben
  - [ ] Koordinaten auf `[290, 640]` ändern: https://github.com/hitobito/hitobito/blob/f79af481af0d6bcee9816acec763a8a463a8be9d/app/domain/export/pdf/invoice/invoice_information.rb#L12
- [ ] Export::Pdf::Invoice::ReceiverAddress überschreiben 
  - [ ] Koordinaten auf `[0, 640]` ändern: https://github.com/hitobito/hitobito/blob/f79af481af0d6bcee9816acec763a8a463a8be9d/app/domain/export/pdf/invoice/receiver_address.rb#L13
- [ ] Export::Pdf::Invoice::Articles überschreiben
  - [ ] total_vat entfernen: https://github.com/hitobito/hitobito/blob/f79af481af0d6bcee9816acec763a8a463a8be9d/app/domain/export/pdf/invoice/articles.rb#L91
  - [ ] evtl. styling anpassen: https://github.com/hitobito/hitobito/blob/f79af481af0d6bcee9816acec763a8a463a8be9d/app/domain/export/pdf/invoice/articles.rb#L75
