### ISSUE TITLE
INVOICE: Zusätzliche Stati auf der Rechnung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#38]
Als Kassier
möchte ich einsehen, ob eine Rechnung teilweise bezahlt wurde oder ob mehr als der Rechnungsbetrag bezahlt wurden
um entsprechende Mahnungen oder Spendenverdankungen auszulösen.

Neu sollen folgende Stati eingeführt werden:
* Teilzahlung
  * Wenn ein Betrag bezahlt wurde aber die Zahlung noch kleiner als der Rechnungsbetrag ist
  * Technisch wird dieser Status wie der Status "gestellt" gehandhabt.
* Überbezahlt 
  * Wenn die Zahlung höher als der Rechnungsbetrag ist
  * Technisch wird dieser Status wie der Status "Bezahlt" gehandhabt.

Der Filter in der Rechnungsansicht `invoices` entsprechend erweitern.

# Tech-Spec

- der Status einer Rechnung soll schnell erkannt werden
- nach Überzahlung oder Unterzahlung soll gefiltert werden können
- Teilzahlung -> partial
- Überzahlung -> excess

# ToDo

- [x] Invoice::STATES, Invoice::STATES_REMINDABLE, Invoice::STATES_PAYABLE erweitern
- [x] Payment#update_invoice anpassen, um den richtigen Status zu setzen:
	- `payment.undercuts?` -> `invoice.state = :partial`
  - `payment.exceeds?` -> `invoice.state = :excess`
- [x] Filterung nach Überzahlung und Teilzahlung prüfen
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Als Kassier "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
