### ISSUE TITLE
SUCHE: Nach Mitgliedernummer und Abonummer suchen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#43]
Nach Mitgliedernummer und Abonummer suchen

Als Benutzer,
möchte ich eine Person aufgrund der Mitgliedernummer oder Abonummer suchen,
um eine Person schnell zu finden.

Neu soll eine Personen gefunden werden. Suchkriterium sind:

* Mitgliedernummer
* Abonummer

# Tech-Spec

- Umsetzung im Wagon, da diese Attribute nur beim SWW vorhanden sind
- Hauptsuche soll erweitert werden

# ToDo

- [x] Suchindex `PersonIndex` erweitern
	- [x] Mitgliedernummer `member_number`
	- [x] Abonummer `magazin_abo_number`
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
