### ISSUE TITLE
INVOICES: Daterange in Rechnungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#58]
Als Rechnungsteller
möchte ich eine bessere Übersicht der Rechnungen haben und nach Datum eingrenzen können
um sehr lange und unübersichtliche Listen zu verhindern.

Wenn sehr viele Rechnungen vorhanden sind, wird die Liste sehr lang und unübersichtlich. Ein besserer Filter bezüglich Datum soll integriert werden.

Zu prüfen ob generell der Datepicker für das Jahr abgelöst werden kann. Dieser kommt u.a. bei events, messages, 

# Mockup

![grafik](https://user-images.githubusercontent.com/95677081/172826802-3ccfd300-2084-4205-8980-3fffa3b53802.png)

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [x] Invoice::Filter anpassen
  - [x] neuer daterange filter: https://github.com/hitobito/hitobito/blob/299af91ded300d10364c31f2625309b6ecc913d6/app/domain/invoice/filter.rb#L20
- [x] View/Controller anpassen
  - [x] `labeled_datetime_field`s für datepickers
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by TheWalkingLeek** [comment]
TODO: Aufräumen & Abschliessen
