### ISSUE TITLE
MESSAGE: Adresse links/rechts als Gruppeneinstellungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#59]
Als Rechnungssteller oder Briefersteller
möchte ich auswählen können ob die Adresse links oder rechts gedruckt angezeigt werden soll,
um auf meine Individuelle Gruppen Eigenschaften reagieren zu können.

Dies Anpassungen sollen für Briefe, Rechnungsbriefe und Rechnungen gelten.

Exakte Positionierung der Adresse wird noch geliefert.

# Mockup
Beispiel über die Konfiguration in der Gruppeneinstellungen (nur Layer):

![image](https://user-images.githubusercontent.com/9592347/173035048-553288f0-aada-4505-b414-6538ee7a9c73.png)

# Tech-Spec
- Neue GroupSetting messages_letter_address_position (gültig für Briefe, Rechnungsbriefe und Rechungen)
  - Neuer Enum Typ mit Radio Buttons: :left, :right
- getter für Position der Address Bounding Box (core)
  -  https://github.com/hitobito/hitobito/blob/master/app/models/group_setting.rb
  - address_position_left, address_position_right
  - dieser Getter can dann im Wagon überschrieben werden
- prüfen ob die Changes Impakt auf Rechnungsanpassungen in anderen Wagons hat (z.B. die Mitte)

# ToDo

- [x] GroupSetting messages_letter_address_position im Core erstellen (default :right), neuen Typ Enum erstellen
- [x] Getter für Positionierung Adress Box mit berücksichtigung left/right:
  - [x] Für Briefe
  - [x] Für Rechnungsbriefe
  - [x] Für Rechnungen
- [x] Spec für Adressposition Links erstellen
- [x] Anpassungen im SWW Wagon
  - [x] Positionierung Adresse rechts gemäss aktuellem Template
  - [x] Positionierung Adresse links gemäss neuen Angaben
  - [x] Positionierung Mitgliederausweis auf der gegenüberliegenden Seite

**Comment by ThomasEllenberger** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-601915cf57bc050017cf9a8c/issues/hitobito/hitobito_sww/59?planning-poker) with ZenHub @kronn @mtnstar @TheWalkingLeek
