### ISSUE TITLE
PEOPLE: Aufräumen Mitgliedernummer

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#66]
Momentan gibt es viele Mitgliedernummern, welche doppelt vergeben sind, davon auch über 1000 welche an mehrere aktive Personen vergeben sind. Für neue Personen wurden ausserdem Mitgliedernummern über 300'000 vergeben (Mitgliederanzahl ist ca. 25'000). Zudem funktioniert aktuell der CSV-Import nicht, weil die Logik zur Vergabe von neuen Mitgliedernummern nicht auf das gleichzeitige Erstellen mehrerer Personen in einer Transaktion ausgelegt ist.

Die SWW möchte gerne...
* eindeutige Mitgliedernummern
* generell möglichst tiefe Mitgliedernummern
* bei möglichst wenigen von früher importierten Personen die Nummer ändern, weil die Kantone sich sonst aufregen
* dass der CSV-Import funktioniert

Nach Absprache mit Loïc setzen wir folgende Lösung um:

### TODO
- [x] Spalte `member_number` auf `manual_member_number` umbenennen
  - [x] sicherstellen dass `manual_member_number` nicht in Exporten und in Index-, Show- und Edit-Ansichten auftaucht
  - [x] Problematische Logik `before_validation`, `set_incremented_member_number` und `next_member_number` (welche nicht transaction-safe ist und race conditions hat) sowie `validates :member_number, uniqueness` **entfernen** (wird später via `validates_by_schema` erledigt, siehe letzter Punkt im TODO)
- [x] Neue Methode `member_number` auf `Person` welche die `manual_member_number` ausgibt falls vorhanden, oder andernfalls die `id + 300_000`
- [x] `manual_member_number` bei allen Personen ohne aktive Rolle auf `NULL` setzen
- [x] `manual_member_number` welche über 300'000 sind auf `NULL` setzen
- [x] Alle dann noch verbleibenden doppelt verwendeten `manual_member_number`s heraussuchen
  - [x] Für jede doppelt verwendete Nummer bei allen bis auf eine Person die `manual_member_number` auf `NULL` setzen. D.h. Wenn `manual_member_number` 1234 von Personen mit IDs 80, 520 und 732 verwendet wird, zum Beispiel die `manual_member_number` bei den Personen 520 und 732 auf `NULL` setzen.
  - [x] **Achtung**: Vorher noch eine Liste mit allen in diesem Schritt veränderten Personen wegspeichern, und an Loïc zustellen, sodass er die Kantone entsprechend informieren kann bei welchen Personen die Mitgliedernummern geändert haben
- [x] Unique Datenbankindex auf der Spalte `manual_member_number` (nicht eine Rails Validation, die Werte müssen wirklich zwingend unique sein)

**Comment by olibrian** [comment]
Gemäss Analyse haben ca 4000 Personen von 32000 Personen eine redundante Nummer. Die Mitgliedernummer ist daher nicht eindeutig. 
Offene Fragen:

- [ ] Soll die Mitgliedernummer eindeutig sein und den Personen potentiell eine neue Nummer erhalten?
- [ ] Ist Option 1 ausreichend?

**Comment by kebpot** [comment]
Option 1 reicht aus. Es ist uns bewusst, dass die Mitgliedernummern zum Teil von verschiedenen FO genutzt werden. Dies wurde beim Import bewusst ignoriert.

**Comment by olibrian** [comment]
Wie viele doppelte Nummern haben wir im System?

**Comment by mtnstar** [comment]
man könnte auch eine neue Nummer einführen, ala SWW Mitgliedernummer. 
diese könnte man einfach vom Primärschlüssel ableiten wie wir das auch bei anderen Instanzen machen. 
so hätten wir für die FOs weiterhin das bestehende Feld für die aktuelle Mitgliedernr und die neue könnte in den nächsten Jahren nach und nach die alte ersetzen.

**Comment by olibrian** [comment]
Nach Rücksprache mit Kunde: Umsetzung der Option 1

**Comment by daniel-illi** [comment]
list all people `id` and their `member_number`:
```
rails r "require 'csv'; rows = Person.pluck(:id, :member_number); puts CSV.generate {|csv| rows.each {|r| csv << r }}"
```
