### ISSUE TITLE
MESSAGE: Position Adresse mittels Offset definieren

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#68]
Als Benutzer welcher ein Brief oder Rechnungsbrief erstellt
möchte ich die Position der Adresse anpassen können
damit sie in mein Couvert oder exakt auf mein Briefpapier passt

Neu soll in den Einstellungen der Gruppe ein Offeset für die Adresse definiert werden können. Bei den SWW betrifft dies auch den Mitgliederausweisteil.

Dieses Offset soll für Rechnungen, Briefe und Rechnungsbriefe berücksichtigt werden. Das Offset soll sowohl positiv wie negativ sein. Eingabe in Millimeter.

# Mockup

Ein Beispiel wie es Smallinvoice gelöst hat:

![image](https://user-images.githubusercontent.com/9592347/186611811-332ea2c2-5298-4460-b9e2-bb3661006a8f.png)

# Tech-Spec

- Umsetzung im SWW Wagon
- Ausschliesslich die Adresse soll von diesen Offsets betroffen sein, alles andere im Brief / in der Rechnung nicht! Sonst öffnen wir uns für endlose Bugs wegen Brief-Layouts für die es keine generische Lösung gibt.

# ToDo

- [x] 2 neue Felder `left_address_offset` und `top_address_offset` in [GroupSetting](https://github.com/hitobito/hitobito/blob/master/app/models/group_setting.rb) einfügen, aber nur im SWW Wagon
- [x] 2 neue Felder für den Mitgliederausweisteil `left_TBD_offset` und `top_TBD_offset` in [GroupSetting](https://github.com/hitobito/hitobito/blob/master/app/models/group_setting.rb) einfügen, aber nur im SWW Wagon
- [ ] Migration erstellen
- [x] PDF Rendering anpassen so dass es diese Offsets berücksichtigt
  - [x] Brief / Rechnungsbrief rendering
  - [x] Rechnung rendering
  - [x] Sowohl die Adress-Offsets wie auch die Mitgliederausweis-Offsets
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
