### ISSUE TITLE
FINANCE: Links im Buchungsbeleg

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#69]
Als Kassier
möchte ich aus dem Buchungsbeleg direkt die entsprechenden Rechnungen ansehen
um eine umfangreiche Suche zu umgehen.

Aufbauend auf https://github.com/hitobito/hitobito_sww/issues/39 soll direkt pro Rechnungsartikel ein Link auf die entsprechende Rechungen erstellt werden. So kann einfach nachvollzogen werden, welche Rechnungen zu den entsprechenden Buchungen geführt haben.

# Tech-Spec

- Schnelle Navigation von Buchungsbeleg zu gefilterter Rechnungsliste
- Es werden nur die Rechnungen des Layers betrachtet
- Umsetzung im Core
- Baut auf hitobito/hitobito#1799 auf
- Link nur bei Rechnungsartikeln einfügen, nicht bei berechneten Spalte wie Teilzahlung und Spenden

# ToDo

- [x] Model/View/Controller anpassen
	- [x] Liste der Rechnungen, die einen bestimmten Rechnungsartikel verwenden, auf Model-Ebene bekommen
	- [x] Liste darstellen, eventuell in einem neuen Controller
	- [x] Views anlegen, sofern dry_crud nicht ausreicht
- [x] Specs schreiben
- [x] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
