### ISSUE TITLE
PEOPLE: Anrede im Export

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#71]
Die SWW brauchen auf ihren Personen-Export eine zusätzliche Spalte Anrede. Im SWW Wagon gibt es auf der Person ein Attribut "Benutzerdefinierte Anrede". Dies wir für spezielle Fälle verwendet. Siehe auch https://github.com/hitobito/hitobito_sww/issues/60

Anforderung seitens SWW:
Auf dem Export "alle Angaben" hat es aktuell eine Spalte "Benutzerdefinierte Anrede" sowie das Feld "Geschlecht". Damit die Anrede nicht nachträglich vie Formel aus dem Geschlecht errechnet werden muss, hätten sie gerne eine zusätzliche Spalte "Anrede" auf dem Export "alle Angaben".
Dies Spalte "Anrede" soll sich wie folgt aus dem Feld "Geschlecht" ableiten: männlich = Herr / weiblich = Frau / unbekannt = unbekannt
Die neue Spalte soll zusätzlich zur Spalte "Benutzerdefinierte Anrede auf dem Export vorhanden sein.

Out of Scope: Prüfen wie eine generische Lösung mit https://github.com/hitobito/hitobito/issues/1141 Sinn machen würde.

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/app/domain/export/tabular/people/people_full.rb

# ToDo

- [x] Neues Computed Attribute 'sww_salutation' im people full export (SWW wagon Erweiterung)
  - name 'sww_salutation' wird hier gewählt damit später beim Harmonisieren der Salutation keinen Konflikt generieren
  - simples Mapping wie oben beschrieben
- [ ] Neue übersetzung im sww wagon für das computed attribute
- [ ] Export manuell testen
