### ISSUE TITLE
PEOPLE: Pflichtfelder Person

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sww#73]
Damit die Personendaten komplett an DONMAN übertragen werden soll auf **Person** folgende Pflichtfelder vorhanden sein:

* last_name + first_name if NOT #company
* company_name if #company

# Tech-Spec

* Validierungen im SWW Wagon

# ToDo

- [ ] Validierungen im Person Model ergänzen
- [ ] Validierung manuell Testen
- [ ] Seeding prüfen/anpassen (Firmen und Personen mit gültigen Daten/Feldern seeden)
- [ ] Changelog Eintrag im Wagon

**Comment by olibrian** [comment]
Validierung erfolgt seitens DONMAN
