### ISSUE TITLE
GROUPS: Ergänzen Struktur Benutzerkonten

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#82]
Die bestehende Meta-Struktur soll durch einen zusätzlichen Layer und eine Rolle ergänzt werden. Diese Rolle soll keine Berechtigung im System haben. Die Personen sollen nur sichtbar für Personen mit Rolle Support auf der Dachebene sein.

Die aktuelle Lösung mit `self.visible_from_above = false` auf der Benutzerkonto Rolle sowie der zusätzlichen Rolle 'Verwalter' scheint aus dieser Sicht gut. Evtl. Verwalter noch in 'Support' renamen

Zugriff für ServiceToken auf Top-Ebene? in Abklärung

Name Gruppentype: Benutzerkonten
Rolle: Benutzerkonto

- Schweizer Wanderwege (SchweizerWanderwege) (Layer)
    - **CMS (Benutzerkonten)** (Layer)
      - **Benutzerkonto: []**
    - Berner Wanderwege (Fachorganisation) (Layer)
    - Argauer Wanderwege (Fachorganisation) (Layer)
    - ...

## Tech spec
- Umsetzung im SWW Wagon

## Todo
- [x] Neuen Layertyp `Group::Benutzerkonten` anlegen
  - [x] Zu den `children` von `Group::SchweizerWanderwege` hinzufügen
  - [x] keine verschachtelten Untergruppen unterstützen
- [x] Neue Rolle `Group::Benutzerkonten::Benutzerkonto` anlegen
  - [x] keine Permissions erteilen
  - [x] `self.visible_from_above = false` auf dieser Rolle setzen
- [x] Überprüfen ob ein Admin auf `Group::SchweizerWanderwege` Zugriff auf diese Personen hat
  - [ ] ~~Idealerweise ist auch der Layer selber nur sichtbar fürs Admins~~ siehe Kommentar
  - [ ] Falls nicht, people_ability im SWW Wagon anpassen, sodass Admins beim SWW das können
  - [ ] Eigentlich müssten sie aber sichtbar sein, gemäss dem [Kommentar](https://github.com/hitobito/hitobito
/blob/master/app/models/role/types.rb#L46..L48) auf `Role::Types`:
    ```ruby
    # Whether a person with this role is visible for somebody
    # with layer_and_below_read permission above the current layer.
    self.visible_from_above = true
    ```
- [x] README.md aktualisieren
- [x] Verwalter in Support renamen

**Comment by TheWalkingLeek** [comment]
Die Gruppen/Personensichtbarkeit einzuschränken ist aufwändiger als in erster Linie vielleicht gedacht.

Wir haben uns der Simplizität nach dafür entschieden im Layer noch eine Rolle "Verwalter" einzuführen.
Diese Rolle sieht dann auch die Benutzer. Die Gruppe selber ist aber für Support und Mitglieder vom Dachverband grundsätzlich immer sichtbar.
Wenn das zu sehr stört würde ich eine umfänglichere Konzeption in einem eigenen Ticket empfehlen

**Comment by olibrian** [comment]
Könntet ihr bitte noch https://github.com/hitobito/hitobito_sww/blob/master/README.md aktualisieren.

**Comment by mtnstar** [comment]
Wir hatten hier spezifiziert das nur Admins die CMS-Benutzer sehen kann. @kebpot ist das ein Muss-Kriterium?
Damit das möglich ist gibt es jetzt eine Rolle Verwalter unter Benutzerkonten. 
Der Nachteil ist, das DONMAN so auch nicht auf diese Einträge zugreifen kann. Soll dies möglich sein?

Wenn ja, würde ich vorschlagen das wir es so vereinfachen das Support und Mitarbeiter des Top-Ebene diese Personen lesen kann. Dann hat auch ein Service Token auf der Top-Ebene Zugriff auf diese Einträge und wir können diese Verwalter Rolle weglassen.

@kebpot was meinst du dazu?

**Comment by mtnstar** [comment]
> Wir hatten hier spezifiziert das nur Admins die CMS-Benutzer sehen kann. @kebpot ist das ein Muss-Kriterium? Damit das möglich ist gibt es jetzt eine Rolle Verwalter unter Benutzerkonten. Der Nachteil ist, das DONMAN so auch nicht auf diese Einträge zugreifen kann. Soll dies möglich sein?
> 
> Wenn ja, würde ich vorschlagen das wir es so vereinfachen das Support und Mitarbeiter des Top-Ebene diese Personen lesen/schreiben kann. Dann hat auch ein Service Token auf der Top-Ebene Zugriff auf diese Einträge und wir können diese Verwalter Rolle weglassen.
> 
> Bzw. wenn es OK ist das Mitarbeiter+Support diese Personen Lesen-/Schreiben darf, dann würde ich es so vereinfachen.
> 
> @kebpot was meinst du dazu?
> 
> @kebpot (Loic) ist laut seinem Autoresponder bis 3. Januar 2023 in den Ferien. Denke wir können gut bis dann warten und das noch fertigstellen wenn wir Feedback von ihm haben.

habe gerade noch Feedback von Loic erhalten. Die Benutzerkonten Personen sollen wirklich nur sichtbar für den Support sein. 

Die Lösung mit der neuen Rolle 'Verwalter' kann von dem her so verwendet werden.

Es muss noch geklärt werden ob ServiceToken (DONMAN) auf der Top-Ebene Zugriff habe müssen.

**Comment by carlobeltrame** [comment]
Ich schliesse dieses Ticket hier mal. Wir können dann noch separat weiterarbeiten, wenn wir genauer wissen ob DONMAN Zugriff auf die Benutzerkonten haben muss oder nicht.
