### ISSUE TITLE
PEOPLE: Zusätzliches Attribut

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#83]
Auf der Person soll ein zusätzliches Attribut erweitert werden. Dieses wird durch die bestehende ID von der aktuellen Webseite befüllt. Diese Feld darf in dem GUI nicht sichtbar sein. Via OIDC soll es mitgegeben werden. Weiter soll es via API abfragbar sein.

Name: sww_cms_profile_id

# Tech-Spec

- Spalte kann noch nicht befüllt werden, wird erst in #84 befüllt

# ToDo

- [x] Migration erstellen: Neue Spalte `:people, :sww_cms_profile_id, :integer` (null: true)
- [x] Neues Attribut `sww_cms_profile_id` zu den Person::INTERNAL_ATTRS hinzufügen
- [x] Im [OIDC Profiles Endpoint](https://github.com/hitobito/hitobito/blob/master/app/controllers/oauth/profiles_controller.rb#L46..L57) mitgeben (natürlich nur im SWW Wagon)
- [x] In der API beim Abrufen von Personendetails exposen (neue JSON API, people#index, people#show, nur lesend), sww_wagon only
- [x] Mit angemessener Rolle "durchklicken"
- [ ] Abklären ob dieses neue Attribut wirklich im JSON:API zurückgegeben werden muss. wenn nicht, dann aus public attrs auf dem Personen model entfernen. falls ja, prüfen ob OK wenn in public_attrs
- [ ] Rubocop fixen
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by olibrian** [comment]
Wir lassen das Attribut in der API wie beschrieben drin. public_attrs sehe ich nicht als Problem.
