### ISSUE TITLE
PEOPLE: Bestehende Benutzerkonten von Webseite übernehmen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#84]
Die bestehenden Benutzerkonten sollen von der aktuellen Webseite übernommen werden. Dazu erhalten wir ein SQL Dump (MySQL) von der Webseite CMS.

Dabei sollen folgende Attribute übernommen werden. Gemäss ersten Recherchen sind folgende Attribute relevant `profile_`*

- ggf weitere Attribute zu klären mit Loic oder CloudTec

| CMS Attribute    | Description                                             |                                       Values                                      |                  Hitobito Attribute                  |
|------------------|---------------------------------------------------------|:---------------------------------------------------------------------------------:|:----------------------------------------------------:|
| profile_id       | unique id, nie leer                                     | 9 - 29424                                                                         | person#sww_cms_profile_id  siehe #83                           |
| profile_prename  | nie leer                                                |                        Felix und Elsbeth, Maxime, A, WEISS                        | person#first_name                                    |
| profile_lastname | nie leer                                                |                     Niederer Dr., schiess, Gautschi-Meier, May                    | person#last_name                                     |
| profile_firm     | Datenqualität Feld? Viele diverse Werte, teilweise leer |          Frau, Monsieur, Privat, WEISS GROUP, 1996, -, Anrede, ----, ...          | person#company_name, if set -> person#company = true |
| profile_address  | nie leer, Datenqualität Feld?                           |         Stift, Belpstrasse 37, Spitzenwiesstrasse, M, Alpenblickstr., ...         | person#address                                       |
| profile_streetnr | teilweise leer                                          |                         4 c, Alte Bahnbergstr, 42, 2b, ...                        | append to person#address                             |
| profile_zip      | nie leer, Datenqualität Feld?                           |                              H2Z0A7, 4242, 01210, ...                             | person#zip_code                                      |
| profile_city     | nie leer                                                |                              w, Nax, Bern, belp, ...                              | person#town                                          |
| profile_country  | teilweise leer                                          | CH, DE, RO, ISO 3166-1 alpha-2                                                    | person#country, assign CH if not defined             |
| profile_email    | teilweise leer                                          | hans.muster@example.com, e-mail nicht importieren falls ungültig (truemail check) | person#email                                         |
| profile_password         |   teilweise leer                                                     | bcrypt mit salt, sha1 hash oder leer                                                                         | person#encrypted_password                                                     |
| profile_password_salt    |   teilweise leer, 06ce406bd9af39b667bd3fdfcab42fe8                                                 |                                                                          | person#sww_legacy_cms_password_salt                                                     | 

Die hier importierten Personen erhalten die Rolle Benutzerkonto unter 'Schweizer Wanderwege' > 'Benutzerkonten' (siehe https://github.com/hitobito/hitobito_sww/issues/82)

## Password Hash und Salt

folgende Password Hashes sind in den 29306 Einträgen der table mod_profile des DB Dumps vorhanden:

* 493 ohne Wert (empty string)
* 26448 mit BCrypt mit blowfish ($2y$)
* 2365 mit SHA1 wert

Hitobito verwendet BCrypt mit blowfish ($2a$). 

über die Unterschiede der BCrypt Algorithmen gibt dieser [Stackoverflow Beitrag](https://stackoverflow.com/questions/15733196/where-2x-prefix-are-used-in-bcrypt) ausführlich Auskunft.

Gemäss diesem [Eintrag](https://stackoverflow.com/questions/20980859/using-bcrypt-ruby-to-validate-hashed-passwords-using-version-2y) sollte ruby-bcrypt mit dem Hash umgehen können. Man muss einfach $2y$ in $2a$ ändern.

Ein Experiment zeigt jedoch das es auch mit $2y$ in Ruby bzw. sogar devise in Hitobito funktioniert:

```
p = Person.first
p.encrypted_password = '$2y$07$BCryptRequires22Chrcte/VlQH0piJtjXl.0t1XkA8pw9dMXTpOq'
p.save!
```

Danach funktioniert ein Login mit diesem User und dem Passwort 'rasmuslerdorf' [aus der PHP doku hier](https://devdocs.io/php/function.password-verify)

### Migration

* Aus Sicherheitsgründen sollen die SHA1 hashes nicht importiert werden
* Natürlich auch nicht die leeren Werte
* Bcrypt hashes werden nur importiert falls ein password_salt vorhanden ist
* Anpassen von devise damit mit den existierenden CMS Passwörtern authentifiziert werden kann #85 

# Tech-Spec

<details>
<summary>describe mod_profile</summary>

```mysql
+----------------------------------+--------------+------+-----+---------+----------------+
| Field                            | Type         | Null | Key | Default | Extra          |
+----------------------------------+--------------+------+-----+---------+----------------+
| profile_id                       | int(11)      | NO   | PRI | NULL    | auto_increment |
| profile_status                   | tinyint(4)   | NO   |     | 0       |                |
| profile_public_from              | int(11)      | NO   |     | 0       |                |
| profile_public_to                | int(11)      | NO   |     | 0       |                |
| profile_mandator                 | int(11)      | NO   |     | 0       |                |
| profile_version_id               | int(11)      | NO   |     | 0       |                |
| profile_version_comment          | text         | NO   |     | NULL    |                |
| profile_groups                   | varchar(255) | NO   |     | 0       |                |
| profile_create_date              | int(11)      | NO   |     | 0       |                |
| profile_create_from              | varchar(50)  | NO   |     |         |                |
| profile_edit_date                | int(11)      | NO   |     | 0       |                |
| profile_edit_from                | varchar(50)  | NO   |     |         |                |
| profile_seo_id                   | varchar(255) | NO   |     |         |                |
| profile_salutation               | tinyint(4)   | NO   |     | NULL    |                |
| profile_prename                  | varchar(100) | NO   |     | NULL    |                |
| profile_lastname                 | varchar(100) | NO   |     | NULL    |                |
| profile_firm                     | varchar(150) | NO   |     | NULL    |                |
| profile_careof                   | varchar(30)  | NO   |     | NULL    |                |
| profile_address                  | varchar(100) | NO   |     | NULL    |                |
| profile_streetnr                 | varchar(20)  | NO   |     | NULL    |                |
| profile_address_add              | varchar(100) | NO   |     | NULL    |                |
| profile_pobox                    | varchar(10)  | NO   |     | NULL    |                |
| profile_zip                      | varchar(10)  | NO   |     | NULL    |                |
| profile_city                     | varchar(100) | NO   |     | NULL    |                |
| profile_country                  | varchar(2)   | NO   |     | NULL    |                |
| profile_birthday                 | int(11)      | NO   |     | NULL    |                |
| profile_email                    | varchar(255) | NO   |     | NULL    |                |
| profile_phone                    | varchar(100) | NO   |     | NULL    |                |
| profile_lang                     | varchar(5)   | NO   |     | NULL    |                |
| profile_client_nr                | varchar(100) | NO   |     | NULL    |                |
| profile_abonr                    | varchar(20)  | NO   |     | NULL    |                |
| profile_patronnr                 | varchar(20)  | NO   |     | NULL    |                |
| profile_member_section           | int(11)      | NO   |     | NULL    |                |
| profile_member_section_confirmed | tinyint(4)   | NO   |     | NULL    |                |
| profile_member_nr                | varchar(100) | NO   |     | NULL    |                |
| profile_member_sections          | varchar(255) | NO   |     | NULL    |                |
| profile_memberships              | varchar(255) | NO   |     | NULL    |                |
| profile_services                 | text         | NO   |     | NULL    |                |
| profile_password                 | varchar(255) | NO   |     | NULL    |                |
| profile_password_salt            | varchar(32)  | NO   |     | NULL    |                |
| profile_masterAddressID          | int(11)      | NO   |     | NULL    |                |
| profile_activation_code          | varchar(32)  | NO   |     | NULL    |                |
| profile_activation_date          | int(11)      | NO   |     | NULL    |                |
| profile_password_code            | varchar(32)  | NO   |     | NULL    |                |
| profile_password_date            | int(11)      | NO   |     | NULL    |                |
| profile_permalogin               | varchar(100) | NO   |     | NULL    |                |
| profile_code_timeout             | int(11)      | NO   |     | NULL    |                |
+----------------------------------+--------------+------+-----+---------+----------------+
```

</details>

* Mysql db dump zu csv konvertieren
* rake import:people_cms

# ToDo

- [x] Validierung das sww_cms_profile_id vorhanden ist, vor dem import prüfen ob alle sww_cms_profile_ids unique sind
- [x] DB Migration für sww_legacy_cms_password_salt
- [x] Import aktuellster [db dump](https://files.puzzle.ch/apps/files/?dir=/swe/projects/SWWA_SchweizerWanderwege/Hitobito/7_Verschiedenes/DBDumpWeb&fileid=4911321) in mysql server (z.B. mysql server hitobito docker setup)
  - erstellen db: `docker-compose exec -it db mysql -u root -p  create database cloudteccms`
  - sowas wie `docker-compose exec -it db mysql -u root -p cloudteccms < dumpfile.sql`
- [x] Konvertieren MySQL table mod_profile zu csv: https://hevodata.com/learn/mysql-export-to-csv/#dump
- [x] Neuer Rake task: import:people_cms in https://github.com/hitobito/hitobito_sww/blob/master/lib/tasks/import.rake
  - source 'db/seeds/production/people_cms.csv'
- [x] neue Klasse DataMigratorCms (inspiriert von https://github.com/hitobito/hitobito_sww/blob/73db04a4b2744467e99541b696aa2a5655541fc8/db/seeds/support/data_migrator.rb#L9)
- [x] TDD ergänzen von https://github.com/hitobito/hitobito_sww/blob/73db04a4b2744467e99541b696aa2a5655541fc8/spec/tasks/import_spec.rb

**Comment by TheWalkingLeek** [comment]
CSV ist hier abgelegt: https://files.puzzle.ch/apps/files/?dir=/swe/projects/SWWA_SchweizerWanderwege/Hitobito/7_Verschiedenes/DBDumpWeb&fileid=4911321
