### ISSUE TITLE
API: Ergänzen Log auf Person mit Autor der Änderung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#92]
Über die Schnittstelle von Donman erhalten wir zusätzliche Information wer Daten geändert hat. Diese Information soll zusätzlich auf Log auf der Person erscheinen. Der Author der Änderung kommt als zusätzliches Attribut seitens Donman bei einem Patch aufruft mit. Aktuell wird nur der Name des API Tokens mitgeschrieben.

Beispielsweise für eine Autor können sein: Post hat eine Adresse geändert, SWW Benutzer hat in Donman was geändert, etc. Dies als reiner Text.

### Tech spec
Umsetzung im SWW Wagon, weil non-standard.
Noch unklar wie die Donman-Schnittstelle die Information liefert. Z.B. als Query Parameter oder als custom HTTP Header?

### TODO
- [x] Neues String-Feld `specific_author` auf `PaperTrail::Version` (nur im SWW Wagon)
- [x] [`PaperTrailed#api_user_for_paper_trail`](https://github.com/hitobito/hitobito/blob/master/app/controllers/concerns/paper_trailed.rb#L29) im Wagon überschreiben
  - [ ] den von Donman allenfalls im Request mitgelieferten Wert auslesen (wir sind in einem Controller Concern und haben Zugriff auf `request`, `session`, etc.). Allenfalls diesen Parameter nur akzeptieren falls wir in einem JSON API Controller sind.
  - [x] Info in `::PaperTrail.request.controller_info` als `specific_author:` mitgeben
- [x] `PaperTrail::VersionDecorator#author_service_token` im Wagon überschreiben und gegebenenfalls `SpezifischerAutor via Service Token: aabbccddeqaopoieraosidf` ausgeben
- [ ] Dokumentation im README ergänzen
- [x] Specs schreiben
- [ ] Manuell testen mit Modifikation via Service Token und via normalen Personen-Login
