### ISSUE TITLE
PEOPLE: Zugriff auf alle Abos für Support

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_sww#94]
Es sollen sämtliche Abos in allen Gruppen für den Support von Dachverband sichtbar sein.

# ToDo

- [x] Berechtigungen prüfen
- [x] Berechtigungen ggf. im Wagon anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by daniel-illi** [comment]
Gefundene Bugs:
* Person kann eigene Abos löschen, auch wenn entsprechende Option auf der Mailinglist deaktiviert ist
