### ISSUE TITLE
Falsche Meldung beim Anmelden an einen Event mit Warteliste

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sww#99]
### Aktuelles Verhalten

Wenn ich mich zu einem Event anmelde, erhalte ich die Meldung: "Es wurde eine Voranmeldung für Teilnahme von Olivier Brian in Anlass 836 erstellt. Die Teilnahme ist noch nicht definitiv und muss von der Kursadministration bestätigt werden."
Dies ist unabhängig ob es eine Warteliste gibt oder nicht.

Dies als Followup von https://github.com/hitobito/hitobito_sww/issues/88

![image](https://user-images.githubusercontent.com/9592347/215429727-7ad0d54f-203b-420a-8a19-965c22c5f3ff.png)

### Gewünschtes Verhalten

Es gibt keine Voranmeldung und eine Kursadministration gibt es auch nicht. Die Meldung soll nicht angezeigt werden.

### Schritte zu reproduzieren

1. Einloggen 
2. Anmelden auf einem Event, wo eine Warteliste aktiviert ist und es genügend freie Plätze hat
3. Info-Meldung anschauen

### Wann ist der Fehler aufgetreten?

30.01.2023. 09:51

### hitobito version

[1.28.41](https://sww.puzzle.ch/de/changelog)

### Organisation

SWW

### Screenshots, weiterer Kontext

Meldung wird hier generiert: https://github.com/hitobito/hitobito/blob/master/app/controllers/event/participations_controller.rb#L316
Übersetzung ist hier: https://github.com/hitobito/hitobito/blob/master/config/locales/views.de.yml#L553
Meldung wurde für https://github.com/hitobito/hitobito_cevi/issues/80 so geschrieben. Aber im Cevi-Wagon gibt es nur auf Kursen eine Warteliste, im Gegensatz zum SWW.

### ToDos
- [x] Beim generieren der Flash-Message beachten ob die Anmeldung tatsächlich auf der Warteliste gelandet ist?
- [x] In der Übersetzung den Begriff "Kursadministration" durch einen allgemeineren Begriff ersetzen, der auch in einem normalen Anlass korrekt sein könnte. Falls kein allgemeingültiger solcher Begriff gefunden wird, Übersetzung einfach im SWW-Wagon anpassen.
- [x] Tests vom Core und von den Cevi-, Jubla- und PBS-Wagons laufen lassen, und allfällige Failures genau untersuchen.

**Comment by daniel-illi** [comment]
Es gibt noch einen Bug beim Anmeldeverhalten, wenn auf dem Event keine Warteliste aktiviert ist.

**Comment by nchiapol** [comment]
@ThomasEllenberger 
Es scheint die aktuellen Änderungen hier haben bei uns einen Bug verursacht. Möglicherweise seit ihr euch dessen bewusst. Für uns ist auf jeden Fall wichtig, dass das gefixt ist, bevor wir Releasen (d.h. möglichst rasch.)
